ACHIEVEMENTS = {
    "first_steps":     {"name": "First Steps",        "emoji": "👶", "description": "Use your first command",                  "reward": 25},
    "rich_beginnings": {"name": "Rich Beginnings",    "emoji": "💰", "description": "Earn your first 5,000 coins",            "reward": 50},
    "high_roller":     {"name": "High Roller",        "emoji": "🎲", "description": "Win 25,000 coins in a single gamble",    "reward": 250},
    "gambler":         {"name": "Gambler",            "emoji": "🎰", "description": "Play 200 gambling games",               "reward": 150},
    "worker_bee":      {"name": "Worker Bee",         "emoji": "🐝", "description": "Complete 100 work shifts",              "reward": 200},
    "survivor":        {"name": "Survivor",           "emoji": "🛡️", "description": "Survive 24 hours without hospital",     "reward": 125},
    "level_10":        {"name": "Rising Star",        "emoji": "⭐", "description": "Reach level 10",                        "reward": 250},
    "level_25":        {"name": "Veteran",            "emoji": "🏅", "description": "Reach level 25",                        "reward": 500},
    "level_50":        {"name": "Legend",             "emoji": "👑", "description": "Reach level 50",                        "reward": 2500},
    "pet_owner":       {"name": "Pet Owner",          "emoji": "🐾", "description": "Adopt a pet",                           "reward": 100},
    "married":         {"name": "Tied the Knot",      "emoji": "💍", "description": "Get married",                           "reward": 150},
    "criminal":        {"name": "Criminal Mastermind","emoji": "🦹", "description": "Commit 100 successful crimes",          "reward": 375},
    "big_spender":     {"name": "Big Spender",        "emoji": "🛍️", "description": "Spend 50,000 coins in the store",      "reward": 250},
    "banker":          {"name": "Banker",             "emoji": "🏦", "description": "Deposit 250,000 coins total",           "reward": 500},
    "unbreakable":     {"name": "Unbreakable",        "emoji": "💪", "description": "Reach max health, hunger, thirst, energy, and hygiene",  "reward": 300},
    "pet_master":      {"name": "Pet Master",         "emoji": "🏆", "description": "Win 50 pet battles",                    "reward": 300},
    "generous":        {"name": "Generous Soul",      "emoji": "🎁", "description": "Gift coins 50 times",                   "reward": 200},
    "streak_7":        {"name": "Weekly Warrior",     "emoji": "🔥", "description": "Maintain a 7-day daily streak",         "reward": 175},
    "streak_30":       {"name": "Unstoppable",        "emoji": "📆", "description": "Maintain a 30-day daily streak",        "reward": 750},
    "quest_master":    {"name": "Quest Master",       "emoji": "📜", "description": "Complete 50 quests",                    "reward": 400},
    "collector":       {"name": "Collector",          "emoji": "💎", "description": "Own 3 or more collectibles",            "reward": 500},
    "wealthy":         {"name": "Wealthy",            "emoji": "🤑", "description": "Have 100,000 coins in wallet + bank",   "reward": 500},
    "frequent_flyer":  {"name": "Frequent Flyer",     "emoji": "✈️", "description": "Work 500 times",                        "reward": 1000},
    "crime_lord":      {"name": "Crime Lord",         "emoji": "🏴", "description": "Commit 500 successful crimes",          "reward": 1000},
    "lucky":           {"name": "Lucky Duck",         "emoji": "🦆", "description": "Win 500 gambling games",                "reward": 500},
    "energizer":       {"name": "Energizer Bunny",    "emoji": "🔋", "description": "Use 10 energy-restoring items",          "reward": 150},
    "clean_freak":     {"name": "Clean Freak",        "emoji": "🧼", "description": "Use 10 hygiene-restoring items",         "reward": 150},
    "homeowner":       {"name": "Homeowner",          "emoji": "🏠", "description": "Buy your first home",                    "reward": 200},
    "property_mogul":  {"name": "Property Mogul",     "emoji": "🏙️", "description": "Own a tier 15+ home",                   "reward": 1000},
    "interior_designer":{"name":"Interior Designer",  "emoji": "🎨", "description": "Own 5 or more decorations",              "reward": 300},
    "settled_down":    {"name": "Settled Down",       "emoji": "🏡", "description": "Upgrade your home 3 times",               "reward": 250},
    "fisherman":       {"name": "Angler",            "emoji": "🎣", "description": "Catch 25 fish",                          "reward": 200},
    "miner":           {"name": "Prospector",        "emoji": "⛏️", "description": "Mine 25 times",                          "reward": 200},
    "explorer":        {"name": "Explorer",          "emoji": "🧭", "description": "Explore 25 times",                       "reward": 250},
    "craftsman":       {"name": "Craftsman",         "emoji": "🔨", "description": "Craft 10 items",                         "reward": 200},
    "treasure_hunter": {"name": "Treasure Hunter",   "emoji": "🗺️", "description": "Find 10 items through exploration",     "reward": 300},
    "quality_collector":{"name":"Quality Collector", "emoji": "🌈", "description": "Discover items of 5 different qualities", "reward": 400},
    "mythic_find":     {"name": "Mythic Discovery",  "emoji": "🔴", "description": "Find a Mythic quality item",             "reward": 1000},
    "well_equipped":   {"name": "Well Equipped",     "emoji": "🎒", "description": "Equip 5 items at once",                  "reward": 200},
    # ─── Phase 5 Achievements ───
    "s_grade":         {"name": "Perfectionist",    "emoji": "🌟", "description": "Get an S grade on a work shift",         "reward": 300},
    "streak_10":       {"name": "On Fire",          "emoji": "🔥", "description": "Reach a 10-shift work streak",           "reward": 250},
    "streak_30":       {"name": "Unstoppable Worker","emoji": "⚡", "description": "Reach a 30-shift work streak",           "reward": 1000},
    "boss_slayer":     {"name": "Boss Slayer",      "emoji": "👹", "description": "Win your first boss shift",               "reward": 500},
    "boss_master":     {"name": "Boss Master",      "emoji": "🏆", "description": "Win 10 boss shifts",                     "reward": 1500},
    "team_player":     {"name": "Team Player",      "emoji": "🤝", "description": "Complete a co-op shift",                 "reward": 200},
    "rep_apprentice":  {"name": "Rising Star",      "emoji": "📚", "description": "Reach Apprentice reputation in any job",  "reward": 150},
    "rep_expert":      {"name": "Expert Worker",    "emoji": "⭐", "description": "Reach Expert reputation in any job",     "reward": 500},
    "rep_legend":      {"name": "Living Legend",    "emoji": "👑", "description": "Reach Legend reputation in any job",     "reward": 2000},
}
