JOB_CATEGORIES = {
    "entry":     {"name": "🧹 Entry Level",      "emoji": "🧹", "description": "Low-skill jobs for beginners. No experience needed!"},
    "service":   {"name": "🍽️ Food & Service",   "emoji": "🍽️", "description": "Serve customers, brew drinks, and cook meals."},
    "trades":    {"name": "🔧 Trades & Labor",   "emoji": "🔧", "description": "Hands-on work: build, fix, and maintain."},
    "medical":   {"name": "⚕️ Medical & Science","emoji": "⚕️", "description": "Heal, research, and push the boundaries of knowledge."},
    "tech":      {"name": "💻 Tech & IT",        "emoji": "💻", "description": "Program, analyze, and build the digital world."},
    "business":  {"name": "💼 Business & Finance","emoji": "💼", "description": "Manage money, lead teams, and run companies."},
    "creative":  {"name": "🎨 Creative & Arts",  "emoji": "🎨", "description": "Entertain, design, and create masterpieces."},
    "transport": {"name": "🚗 Transport & Logistics","emoji": "🚗", "description": "Move people and goods across the world."},
}

JOBS = {
    # ─── Entry Level (25) ───
    "beggar":          {"name": "🧎 Beggar",            "base_pay": 5,    "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Beg on the streets for spare change."},
    "busker":          {"name": "🎸 Street Busker",     "base_pay": 8,    "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Play music on the corner for tips."},
    "leafleter":       {"name": "📋 Leaflet Distributor","base_pay": 7,   "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Hand out flyers on busy streets."},
    "window_washer":   {"name": "🪟 Window Washer",     "base_pay": 9,    "min_level": 1,  "cooldown": 150,  "category": "entry",    "description": "Wash shop windows for small fees."},
    "dog_walker":      {"name": "🐕 Dog Walker",        "base_pay": 10,   "min_level": 1,  "cooldown": 180,  "category": "entry",    "description": "Walk dogs for busy pet owners."},
    "recycler":        {"name": "♻️ Recycler",          "base_pay": 8,    "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Collect cans and bottles for recycling money."},
    "shoe_shiner":     {"name": "👞 Shoe Shiner",       "base_pay": 9,    "min_level": 1,  "cooldown": 150,  "category": "entry",    "description": "Shine shoes at the train station."},
    "newspaper":       {"name": "📰 Paper Round",       "base_pay": 7,    "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Deliver newspapers early mornings."},
    "car_wash":        {"name": "🚿 Car Wash Attendant","base_pay": 11,   "min_level": 2,  "cooldown": 180,  "category": "entry",    "description": "Wash cars by hand at a local car wash."},
    "trolley":         {"name": "🛒 Trolley Collector", "base_pay": 10,   "min_level": 1,  "cooldown": 180,  "category": "entry",    "description": "Collect shopping trolleys from the parking lot."},
    "plant_waterer":   {"name": "🪴 Plant Waterer",     "base_pay": 9,    "min_level": 1,  "cooldown": 150,  "category": "entry",    "description": "Water office plants for small businesses."},
    "litter_picker":   {"name": "🗑️ Litter Picker",     "base_pay": 8,    "min_level": 1,  "cooldown": 120,  "category": "entry",    "description": "Pick up litter in parks and public spaces."},
    "sign_holder":     {"name": "🪧 Sign Holder",       "base_pay": 10,   "min_level": 1,  "cooldown": 180,  "category": "entry",    "description": "Hold advertising signs on street corners."},
    "survey_taker":    {"name": "📝 Survey Taker",      "base_pay": 11,   "min_level": 2,  "cooldown": 180,  "category": "entry",    "description": "Conduct street surveys for market research."},
    "moving_helper":   {"name": "📦 Moving Helper",     "base_pay": 12,   "min_level": 2,  "cooldown": 240,  "category": "entry",    "description": "Help people move furniture and boxes."},
    "ticket_tearer":   {"name": "🎟️ Ticket Tearer",     "base_pay": 10,   "min_level": 1,  "cooldown": 180,  "category": "entry",    "description": "Tear tickets at the cinema entrance."},
    "ice_cream":       {"name": "🍦 Ice Cream Vendor",  "base_pay": 11,   "min_level": 2,  "cooldown": 180,  "category": "entry",    "description": "Sell ice cream from a cart in the park."},
    "balloon_seller":  {"name": "🎈 Balloon Seller",    "base_pay": 9,    "min_level": 1,  "cooldown": 150,  "category": "entry",    "description": "Sell balloons at fairs and events."},
    "parking_attend":  {"name": "🅿️ Parking Attendant", "base_pay": 12,   "min_level": 2,  "cooldown": 240,  "category": "entry",    "description": "Collect parking fees and issue tickets."},
    "garden_helper":   {"name": "🌱 Garden Helper",     "base_pay": 11,   "min_level": 2,  "cooldown": 180,  "category": "entry",    "description": "Pull weeds and help gardeners."},
    "shelf_stocker":   {"name": "🛍️ Shelf Stocker",     "base_pay": 12,   "min_level": 2,  "cooldown": 240,  "category": "entry",    "description": "Stock shelves at the supermarket."},
    "janitor":         {"name": "🧹 Janitor",           "base_pay": 13,   "min_level": 2,  "cooldown": 240,  "category": "entry",    "description": "Clean floors and empty trash bins."},
    "laundry":         {"name": "👕 Laundry Attendant", "base_pay": 12,   "min_level": 2,  "cooldown": 240,  "category": "entry",    "description": "Wash, dry, and fold laundry at a laundromat."},
    "food_sample":     {"name": "🍽️ Food Sample Giver", "base_pay": 11,   "min_level": 2,  "cooldown": 180,  "category": "entry",    "description": "Hand out free food samples at the mall."},
    "cart_pusher":     {"name": "🛒 Cart Pusher",       "base_pay": 10,   "min_level": 1,  "cooldown": 180,  "category": "entry",    "description": "Push carts at the market for customers."},

    # ─── Food & Service (25) ───
    "barista":         {"name": "☕ Barista",           "base_pay": 35,   "min_level": 4,  "cooldown": 900,  "category": "service",   "description": "Brew coffee and serve customers."},
    "chef":            {"name": "👨‍🍳 Chef",             "base_pay": 40,   "min_level": 5,  "cooldown": 1200, "category": "service",   "description": "Cook meals at a fancy restaurant."},
    "waiter":          {"name": "🤵 Waiter",            "base_pay": 25,   "min_level": 3,  "cooldown": 600,  "category": "service",   "description": "Serve food and take orders at a restaurant."},
    "bartender":       {"name": "🍸 Bartender",         "base_pay": 38,   "min_level": 5,  "cooldown": 900,  "category": "service",   "description": "Mix drinks at a busy bar."},
    "fast_food":       {"name": "🍔 Fast Food Worker",  "base_pay": 18,   "min_level": 2,  "cooldown": 480,  "category": "service",   "description": "Flip burgers and take orders at a drive-thru."},
    "sushi_chef":      {"name": "🍣 Sushi Chef",        "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "service",   "description": "Craft delicate sushi rolls with precision."},
    "pastry_chef":     {"name": "🧁 Pastry Chef",       "base_pay": 50,   "min_level": 6,  "cooldown": 1200, "category": "service",   "description": "Bake pastries, cakes, and desserts."},
    "sommelier":       {"name": "🍷 Sommelier",         "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "service",   "description": "Pair wines with fine dining experiences."},
    "food_truck":      {"name": "🚚 Food Truck Owner",  "base_pay": 45,   "min_level": 6,  "cooldown": 1200, "category": "service",   "description": "Run your own food truck on the streets."},
    "caterer":         {"name": "🍱 Caterer",           "base_pay": 42,   "min_level": 5,  "cooldown": 1200, "category": "service",   "description": "Prepare and deliver food for events."},
    "butcher":         {"name": "🥩 Butcher",           "base_pay": 35,   "min_level": 4,  "cooldown": 900,  "category": "service",   "description": "Cut and prepare meat for customers."},
    "baker":           {"name": "🥖 Baker",             "base_pay": 32,   "min_level": 4,  "cooldown": 900,  "category": "service",   "description": "Bake fresh bread every morning."},
    "host":            {"name": "🎩 Restaurant Host",   "base_pay": 22,   "min_level": 3,  "cooldown": 600,  "category": "service",   "description": "Greet guests and manage reservations."},
    "barista_master":  {"name": "☕ Master Barista",    "base_pay": 60,   "min_level": 8,  "cooldown": 1800, "category": "service",   "description": "Craft award-winning latte art and brews."},
    "sous_chef":       {"name": "🔪 Sous Chef",         "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "service",   "description": "Second-in-command in a professional kitchen."},
    "nutritionist":    {"name": "🥗 Nutritionist",      "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "service",   "description": "Plan meals and advise clients on healthy eating."},
    "food_critic":     {"name": "✍️ Food Critic",       "base_pay": 75,   "min_level": 10, "cooldown": 2400, "category": "service",   "description": "Review restaurants for a food magazine."},
    "hotel_manager":   {"name": "🏨 Hotel Manager",     "base_pay": 85,   "min_level": 11, "cooldown": 2400, "category": "service",   "description": "Manage a luxury hotel and its staff."},
    "event_planner":   {"name": "🎉 Event Planner",     "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "service",   "description": "Plan weddings, parties, and corporate events."},
    "sommelier_master":{"name": "🍾 Master Sommelier",  "base_pay": 95,   "min_level": 12, "cooldown": 3000, "category": "service",   "description": "Top-tier wine expert at a Michelin restaurant."},
    "mixologist":      {"name": "🍹 Mixologist",        "base_pay": 58,   "min_level": 7,  "cooldown": 1500, "category": "service",   "description": "Create innovative cocktail recipes."},
    "chocolatier":     {"name": "🍫 Chocolatier",       "base_pay": 52,   "min_level": 6,  "cooldown": 1200, "category": "service",   "description": "Craft artisan chocolates and truffles."},
    "teasomm":         {"name": "🍵 Tea Sommelier",     "base_pay": 48,   "min_level": 6,  "cooldown": 1200, "category": "service",   "description": "Curate and serve premium teas."},
    "private_chef":    {"name": "🍳 Private Chef",      "base_pay": 90,   "min_level": 11, "cooldown": 2400, "category": "service",   "description": "Cook exclusively for wealthy clients."},
    "restaurateur":    {"name": "🍽️ Restaurateur",      "base_pay": 110,  "min_level": 14, "cooldown": 3600, "category": "service",   "description": "Own and operate your own restaurant empire."},

    # ─── Trades & Labor (25) ───
    "mechanic":        {"name": "🔧 Mechanic",          "base_pay": 60,   "min_level": 8,  "cooldown": 1800, "category": "trades",   "description": "Fix cars in the auto shop."},
    "electrician":     {"name": "⚡ Electrician",       "base_pay": 80,   "min_level": 10, "cooldown": 2400, "category": "trades",   "description": "Wire buildings and fix electrical systems."},
    "plumber":         {"name": "🚿 Plumber",           "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "trades",   "description": "Fix pipes and plumbing systems."},
    "carpenter":       {"name": "🪚 Carpenter",         "base_pay": 50,   "min_level": 6,  "cooldown": 1200, "category": "trades",   "description": "Build furniture and wooden structures."},
    "welder":          {"name": "🔥 Welder",            "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "trades",   "description": "Fuse metal with extreme heat and precision."},
    "construction":    {"name": "🏗️ Construction Worker","base_pay": 40,  "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Build houses and commercial buildings."},
    "roofer":          {"name": "🏠 Roofer",            "base_pay": 48,   "min_level": 6,  "cooldown": 1200, "category": "trades",   "description": "Install and repair roofs in all weather."},
    "painter":         {"name": "🎨 House Painter",     "base_pay": 42,   "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Paint interiors and exteriors of buildings."},
    "mason":           {"name": "🧱 Mason",             "base_pay": 52,   "min_level": 6,  "cooldown": 1200, "category": "trades",   "description": "Lay bricks and stone for walls and buildings."},
    "tiler":           {"name": "🔲 Tiler",             "base_pay": 45,   "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Install tiles on floors and walls."},
    "insulator":       {"name": "🧊 Insulator",         "base_pay": 46,   "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Install insulation in buildings."},
    "glazier":         {"name": "🪟 Glazier",           "base_pay": 54,   "min_level": 7,  "cooldown": 1500, "category": "trades",   "description": "Cut and install glass for windows."},
    "hvac":            {"name": "❄️ HVAC Technician",   "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "trades",   "description": "Install and repair heating and cooling systems."},
    "landscaper":      {"name": "🌳 Landscaper",        "base_pay": 38,   "min_level": 4,  "cooldown": 900,  "category": "trades",   "description": "Design and maintain outdoor spaces."},
    "foreman":         {"name": "👷 Foreman",           "base_pay": 85,   "min_level": 11, "cooldown": 2400, "category": "trades",   "description": "Supervise construction crews on site."},
    "surveyor":        {"name": "📐 Surveyor",          "base_pay": 75,   "min_level": 10, "cooldown": 1800, "category": "trades",   "description": "Measure land and map construction sites."},
    "demolition":      {"name": "💥 Demolition Worker", "base_pay": 58,   "min_level": 7,  "cooldown": 1500, "category": "trades",   "description": "Tear down old buildings safely."},
    "scaffolder":      {"name": "🪜 Scaffolder",        "base_pay": 44,   "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Build temporary structures for construction."},
    "floor_layer":     {"name": "🪵 Floor Layer",       "base_pay": 47,   "min_level": 5,  "cooldown": 1200, "category": "trades",   "description": "Install hardwood, carpet, and tile flooring."},
    "locksmith":       {"name": "🔑 Locksmith",         "base_pay": 62,   "min_level": 8,  "cooldown": 1800, "category": "trades",   "description": "Pick locks and cut keys for clients."},
    "heavy_equipment": {"name": "🚜 Heavy Equipment Op","base_pay": 72,   "min_level": 9,  "cooldown": 1800, "category": "trades",   "description": "Operate cranes, bulldozers, and excavators."},
    "steelworker":     {"name": "🏗️ Steelworker",       "base_pay": 78,   "min_level": 10, "cooldown": 2400, "category": "trades",   "description": "Work with steel beams on skyscrapers."},
    "elevator_fix":    {"name": "🛗 Elevator Mechanic", "base_pay": 82,   "min_level": 10, "cooldown": 2400, "category": "trades",   "description": "Repair and install elevators."},
    "solar_installer": {"name": "☀️ Solar Panel Installer","base_pay": 68,"min_level": 8,  "cooldown": 1800, "category": "trades",   "description": "Install solar panels on rooftops."},
    "contractor":      {"name": "📋 General Contractor","base_pay": 100,  "min_level": 13, "cooldown": 3000, "category": "trades",   "description": "Oversee entire construction projects from start to finish."},

    # ─── Medical & Science (25) ───
    "doctor":          {"name": "👨‍⚕️ Doctor",          "base_pay": 100,  "min_level": 12, "cooldown": 3600, "category": "medical",   "description": "Save lives at the hospital."},
    "nurse":           {"name": "💉 Nurse",             "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "medical",   "description": "Care for patients and assist doctors."},
    "paramedic":       {"name": "🚑 Paramedic",         "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "medical",   "description": "Respond to emergencies and save lives on the go."},
    "pharmacist":      {"name": "💊 Pharmacist",        "base_pay": 85,   "min_level": 11, "cooldown": 2400, "category": "medical",   "description": "Dispense medication and advise patients."},
    "dentist":         {"name": "🦷 Dentist",           "base_pay": 90,   "min_level": 11, "cooldown": 2400, "category": "medical",   "description": "Fix teeth and brighten smiles."},
    "surgeon":         {"name": "🔬 Surgeon",           "base_pay": 150,  "min_level": 15, "cooldown": 3600, "category": "medical",   "description": "Perform complex surgeries in the operating room."},
    "vet":             {"name": "🐾 Veterinarian",      "base_pay": 75,   "min_level": 10, "cooldown": 1800, "category": "medical",   "description": "Treat sick and injured animals."},
    "therapist":       {"name": "🛋️ Therapist",         "base_pay": 80,   "min_level": 10, "cooldown": 2400, "category": "medical",   "description": "Help people through mental health challenges."},
    "radiologist":     {"name": "📷 Radiologist",       "base_pay": 110,  "min_level": 13, "cooldown": 3000, "category": "medical",   "description": "Read X-rays and MRI scans."},
    "lab_tech":        {"name": "🧪 Lab Technician",    "base_pay": 50,   "min_level": 6,  "cooldown": 1200, "category": "medical",   "description": "Run tests on blood and tissue samples."},
    "research_sci":    {"name": "🔬 Research Scientist","base_pay": 120,  "min_level": 14, "cooldown": 3600, "category": "medical",   "description": "Conduct experiments and publish findings."},
    "biologist":       {"name": "🧬 Biologist",         "base_pay": 95,   "min_level": 12, "cooldown": 2400, "category": "medical",   "description": "Study living organisms and ecosystems."},
    "chemist":         {"name": "⚗️ Chemist",           "base_pay": 88,   "min_level": 11, "cooldown": 2400, "category": "medical",   "description": "Develop new compounds and materials."},
    "physicist":       {"name": "🔭 Physicist",         "base_pay": 130,  "min_level": 15, "cooldown": 3600, "category": "medical",   "description": "Study the fundamental laws of the universe."},
    "astronomer":      {"name": "🌌 Astronomer",        "base_pay": 115,  "min_level": 14, "cooldown": 3000, "category": "medical",   "description": "Observe stars and map the cosmos."},
    "geneticist":      {"name": "🧬 Geneticist",        "base_pay": 140,  "min_level": 16, "cooldown": 3600, "category": "medical",   "description": "Study DNA and genetic disorders."},
    "neurosurgeon":    {"name": "🧠 Neurosurgeon",      "base_pay": 200,  "min_level": 20, "cooldown": 7200, "category": "medical",   "description": "Perform delicate brain surgeries."},
    "cardiologist":    {"name": "❤️ Cardiologist",      "base_pay": 180,  "min_level": 18, "cooldown": 3600, "category": "medical",   "description": "Specialize in heart health and surgery."},
    "pediatrician":    {"name": "👶 Pediatrician",      "base_pay": 105,  "min_level": 13, "cooldown": 3000, "category": "medical",   "description": "Care for children and infants."},
    "optometrist":     {"name": "👁️ Optometrist",       "base_pay": 78,   "min_level": 10, "cooldown": 1800, "category": "medical",   "description": "Test vision and prescribe glasses."},
    "physical_ther":   {"name": "💪 Physical Therapist","base_pay": 72,   "min_level": 9,  "cooldown": 1800, "category": "medical",   "description": "Help patients recover mobility after injuries."},
    "med_researcher":  {"name": "🧫 Medical Researcher","base_pay": 125,  "min_level": 15, "cooldown": 3600, "category": "medical",   "description": "Develop new treatments and cures."},
    "epidemiologist":  {"name": "😷 Epidemiologist",    "base_pay": 135,  "min_level": 16, "cooldown": 3600, "category": "medical",   "description": "Track and prevent disease outbreaks."},
    "toxicologist":    {"name": "☠️ Toxicologist",      "base_pay": 115,  "min_level": 14, "cooldown": 3000, "category": "medical",   "description": "Study poisons and their effects on the body."},
    "astronaut":       {"name": "🚀 Astronaut",         "base_pay": 350,  "min_level": 25, "cooldown": 7200, "category": "medical",   "description": "Explore space and conduct research in orbit."},

    # ─── Tech & IT (25) ───
    "programmer":      {"name": "💻 Programmer",        "base_pay": 150,  "min_level": 15, "cooldown": 3600, "category": "tech",     "description": "Write code for tech companies."},
    "it_support":      {"name": "🎧 IT Support",        "base_pay": 45,   "min_level": 5,  "cooldown": 1200, "category": "tech",     "description": "Help people fix their computer problems."},
    "web_dev":         {"name": "🌐 Web Developer",     "base_pay": 90,   "min_level": 11, "cooldown": 2400, "category": "tech",     "description": "Build websites and web applications."},
    "data_analyst":    {"name": "📊 Data Analyst",      "base_pay": 100,  "min_level": 12, "cooldown": 2400, "category": "tech",     "description": "Analyze data to find trends and insights."},
    "sysadmin":        {"name": "🖥️ Sysadmin",          "base_pay": 85,   "min_level": 10, "cooldown": 2400, "category": "tech",     "description": "Manage servers and keep systems running."},
    "ux_designer":     {"name": "🎨 UX Designer",       "base_pay": 95,   "min_level": 12, "cooldown": 2400, "category": "tech",     "description": "Design intuitive user interfaces."},
    "game_dev":        {"name": "🎮 Game Developer",    "base_pay": 110,  "min_level": 13, "cooldown": 3000, "category": "tech",     "description": "Create video games for millions of players."},
    "data_scientist":  {"name": "📈 Data Scientist",    "base_pay": 140,  "min_level": 15, "cooldown": 3600, "category": "tech",     "description": "Build ML models and find patterns in big data."},
    "devops":          {"name": "⚙️ DevOps Engineer",   "base_pay": 130,  "min_level": 14, "cooldown": 3600, "category": "tech",     "description": "Automate deployments and manage infrastructure."},
    "security_analyst":{"name": "🔒 Security Analyst",  "base_pay": 120,  "min_level": 14, "cooldown": 3000, "category": "tech",     "description": "Protect systems from cyber threats."},
    "mobile_dev":      {"name": "📱 Mobile Developer",  "base_pay": 105,  "min_level": 13, "cooldown": 3000, "category": "tech",     "description": "Build apps for iOS and Android."},
    "ai_engineer":     {"name": "🤖 AI Engineer",       "base_pay": 180,  "min_level": 18, "cooldown": 3600, "category": "tech",     "description": "Build neural networks and AI systems."},
    "cloud_arch":      {"name": "☁️ Cloud Architect",   "base_pay": 160,  "min_level": 16, "cooldown": 3600, "category": "tech",     "description": "Design cloud infrastructure at scale."},
    "blockchain_dev":  {"name": "⛓️ Blockchain Dev",    "base_pay": 170,  "min_level": 17, "cooldown": 3600, "category": "tech",     "description": "Build decentralized apps and smart contracts."},
    "qa_tester":       {"name": "🐛 QA Tester",         "base_pay": 60,   "min_level": 7,  "cooldown": 1500, "category": "tech",     "description": "Find bugs before users do."},
    "tech_writer":     {"name": "📝 Tech Writer",       "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "tech",     "description": "Write documentation and guides."},
    "product_manager": {"name": "📋 Product Manager",   "base_pay": 145,  "min_level": 15, "cooldown": 3600, "category": "tech",     "description": "Lead product development from idea to launch."},
    "db_admin":        {"name": "🗄️ Database Admin",    "base_pay": 115,  "min_level": 13, "cooldown": 3000, "category": "tech",     "description": "Manage databases and ensure data integrity."},
    "network_eng":     {"name": "🌐 Network Engineer",  "base_pay": 108,  "min_level": 13, "cooldown": 3000, "category": "tech",     "description": "Design and maintain computer networks."},
    "frontend_dev":    {"name": "🖥️ Frontend Developer","base_pay": 92,   "min_level": 11, "cooldown": 2400, "category": "tech",     "description": "Build beautiful user interfaces with JS."},
    "backend_dev":     {"name": "⚙️ Backend Developer", "base_pay": 125,  "min_level": 14, "cooldown": 3000, "category": "tech",     "description": "Build server-side logic and APIs."},
    "pentester":       {"name": "🕵️ Penetration Tester","base_pay": 155,  "min_level": 16, "cooldown": 3600, "category": "tech",     "description": "Hack systems legally to find vulnerabilities."},
    "ml_engineer":     {"name": "🧠 ML Engineer",       "base_pay": 190,  "min_level": 19, "cooldown": 3600, "category": "tech",     "description": "Deploy machine learning models to production."},
    "cto":             {"name": "👔 CTO",               "base_pay": 300,  "min_level": 22, "cooldown": 7200, "category": "tech",     "description": "Lead the entire tech strategy of a company."},
    "hacker":          {"name": "💻 Ethical Hacker",    "base_pay": 165,  "min_level": 17, "cooldown": 3600, "category": "tech",     "description": "Get paid to break into systems — legally."},

    # ─── Business & Finance (25) ───
    "ceo":             {"name": "👔 CEO",               "base_pay": 500,  "min_level": 30, "cooldown": 7200, "category": "business", "description": "Run a multi-million dollar company."},
    "bank_teller":     {"name": "🏦 Bank Teller",       "base_pay": 40,   "min_level": 5,  "cooldown": 1200, "category": "business", "description": "Handle deposits and withdrawals at a bank."},
    "accountant":      {"name": "🧮 Accountant",        "base_pay": 75,   "min_level": 10, "cooldown": 1800, "category": "business", "description": "Balance books and prepare taxes."},
    "sales_rep":       {"name": "🤝 Sales Rep",         "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "business", "description": "Sell products and earn commissions."},
    "real_estate":     {"name": "🏠 Real Estate Agent", "base_pay": 85,   "min_level": 11, "cooldown": 2400, "category": "business", "description": "Buy and sell properties for clients."},
    "stockbroker":     {"name": "📈 Stockbroker",       "base_pay": 130,  "min_level": 15, "cooldown": 3600, "category": "business", "description": "Trade stocks on behalf of clients."},
    "financial_adv":   {"name": "💰 Financial Advisor", "base_pay": 110,  "min_level": 13, "cooldown": 3000, "category": "business", "description": "Advise clients on investments and savings."},
    "manager":         {"name": "📋 Manager",           "base_pay": 80,   "min_level": 10, "cooldown": 2400, "category": "business", "description": "Manage a team and oversee operations."},
    "hr_specialist":   {"name": "👤 HR Specialist",     "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "business", "description": "Hire employees and handle workplace issues."},
    "marketing":       {"name": "📢 Marketing Specialist","base_pay": 70, "min_level": 9,  "cooldown": 1800, "category": "business", "description": "Run ad campaigns and build brand awareness."},
    "consultant":      {"name": "💼 Consultant",        "base_pay": 120,  "min_level": 14, "cooldown": 3000, "category": "business", "description": "Advise companies on strategy and growth."},
    "auditor":         {"name": "🔍 Auditor",           "base_pay": 95,   "min_level": 12, "cooldown": 2400, "category": "business", "description": "Inspect financial records for accuracy."},
    "loan_officer":    {"name": "💵 Loan Officer",      "base_pay": 78,   "min_level": 10, "cooldown": 1800, "category": "business", "description": "Approve or deny loan applications."},
    "insurance":       {"name": "🛡️ Insurance Agent",   "base_pay": 62,   "min_level": 8,  "cooldown": 1800, "category": "business", "description": "Sell insurance policies to clients."},
    "bookkeeper":      {"name": "📒 Bookkeeper",        "base_pay": 48,   "min_level": 6,  "cooldown": 1200, "category": "business", "description": "Record daily financial transactions."},
    "tax_prep":        {"name": "🧾 Tax Preparer",      "base_pay": 68,   "min_level": 9,  "cooldown": 1800, "category": "business", "description": "Prepare tax returns for individuals and businesses."},
    "investment_bank": {"name": "🏦 Investment Banker", "base_pay": 220,  "min_level": 20, "cooldown": 7200, "category": "business", "description": "Advise on mergers, acquisitions, and IPOs."},
    "venture_cap":     {"name": "💸 Venture Capitalist","base_pay": 280,  "min_level": 24, "cooldown": 7200, "category": "business", "description": "Invest in promising startups."},
    "hedge_fund":      {"name": "📊 Hedge Fund Manager","base_pay": 350,  "min_level": 28, "cooldown": 7200, "category": "business", "description": "Manage a hedge fund and maximize returns."},
    "entrepreneur":    {"name": "🚀 Entrepreneur",      "base_pay": 160,  "min_level": 16, "cooldown": 3600, "category": "business", "description": "Start your own business from scratch."},
    "cfo":             {"name": "💰 CFO",               "base_pay": 400,  "min_level": 28, "cooldown": 7200, "category": "business", "description": "Manage the finances of a major corporation."},
    "coo":             {"name": "⚙️ COO",               "base_pay": 380,  "min_level": 27, "cooldown": 7200, "category": "business", "description": "Oversee daily operations of a company."},
    "trader":          {"name": "📉 Day Trader",        "base_pay": 145,  "min_level": 15, "cooldown": 3600, "category": "business", "description": "Trade stocks daily from your home office."},
    "negotiator":      {"name": "🤝 Negotiator",        "base_pay": 135,  "min_level": 15, "cooldown": 3600, "category": "business", "description": "Negotiate deals and contracts for corporations."},
    "magnate":         {"name": "👑 Business Magnate",  "base_pay": 600,  "min_level": 35, "cooldown": 7200, "category": "business", "description": "Own a vast business empire across multiple industries."},

    # ─── Creative & Arts (25) ───
    "artist":          {"name": "🎨 Artist",            "base_pay": 45,   "min_level": 5,  "cooldown": 1200, "category": "creative", "description": "Paint and sell original artwork."},
    "musician":        {"name": "🎵 Musician",          "base_pay": 50,   "min_level": 6,  "cooldown": 1200, "category": "creative", "description": "Perform music at venues and events."},
    "writer":          {"name": "✍️ Writer",            "base_pay": 42,   "min_level": 5,  "cooldown": 1200, "category": "creative", "description": "Write novels, articles, and stories."},
    "photographer":    {"name": "📷 Photographer",      "base_pay": 48,   "min_level": 5,  "cooldown": 1200, "category": "creative", "description": "Take photos for clients and events."},
    "graphic_design":  {"name": "🖌️ Graphic Designer", "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "creative", "description": "Design logos, posters, and brand materials."},
    "actor":           {"name": "🎭 Actor",             "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "creative", "description": "Perform in plays, films, and TV shows."},
    "filmmaker":       {"name": "🎬 Filmmaker",         "base_pay": 85,   "min_level": 11, "cooldown": 2400, "category": "creative", "description": "Direct and produce films."},
    "animator":        {"name": "🎞️ Animator",          "base_pay": 75,   "min_level": 10, "cooldown": 1800, "category": "creative", "description": "Create animations for film and games."},
    "fashion_design":  {"name": "👗 Fashion Designer",  "base_pay": 90,   "min_level": 11, "cooldown": 2400, "category": "creative", "description": "Design clothing and accessories."},
    "interior_design": {"name": "🛋️ Interior Designer", "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "creative", "description": "Design beautiful indoor spaces."},
    "architect":       {"name": "🏛️ Architect",         "base_pay": 110,  "min_level": 13, "cooldown": 3000, "category": "creative", "description": "Design buildings and structures."},
    "sculptor":        {"name": "🗿 Sculptor",          "base_pay": 58,   "min_level": 7,  "cooldown": 1500, "category": "creative", "description": "Create sculptures from stone, metal, and clay."},
    "tattoo_artist":   {"name": "🖋️ Tattoo Artist",    "base_pay": 62,   "min_level": 8,  "cooldown": 1800, "category": "creative", "description": "Ink permanent art on people's skin."},
    "makeup_artist":   {"name": "💄 Makeup Artist",     "base_pay": 52,   "min_level": 6,  "cooldown": 1200, "category": "creative", "description": "Do makeup for film, TV, and events."},
    "dancer":          {"name": "💃 Dancer",            "base_pay": 48,   "min_level": 6,  "cooldown": 1200, "category": "creative", "description": "Perform dance routines on stage."},
    "comedian":        {"name": "🎤 Comedian",          "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "creative", "description": "Tell jokes and perform stand-up comedy."},
    "dj":              {"name": "🎧 DJ",                "base_pay": 70,   "min_level": 9,  "cooldown": 1800, "category": "creative", "description": "Mix tracks at clubs and festivals."},
    "producer":        {"name": "🎹 Music Producer",    "base_pay": 95,   "min_level": 12, "cooldown": 2400, "category": "creative", "description": "Produce tracks for recording artists."},
    "director":        {"name": "🎬 Film Director",     "base_pay": 130,  "min_level": 15, "cooldown": 3600, "category": "creative", "description": "Direct major motion pictures."},
    "novelist":        {"name": "📚 Novelist",          "base_pay": 80,   "min_level": 10, "cooldown": 1800, "category": "creative", "description": "Write bestselling novels."},
    "jeweler":         {"name": "💎 Jeweler",           "base_pay": 72,   "min_level": 9,  "cooldown": 1800, "category": "creative", "description": "Craft fine jewelry from gold and gems."},
    "potter":          {"name": "🏺 Potter",            "base_pay": 40,   "min_level": 5,  "cooldown": 1200, "category": "creative", "description": "Throw clay and create ceramics."},
    "stunt_double":    {"name": "🤸 Stunt Double",      "base_pay": 88,   "min_level": 11, "cooldown": 2400, "category": "creative", "description": "Perform dangerous stunts on film sets."},
    "voice_actor":     {"name": "🎙️ Voice Actor",       "base_pay": 68,   "min_level": 9,  "cooldown": 1800, "category": "creative", "description": "Voice characters for animation and games."},
    "maestro":         {"name": "🎼 Maestro",           "base_pay": 150,  "min_level": 16, "cooldown": 3600, "category": "creative", "description": "Conduct world-class symphony orchestras."},

    # ─── Transport & Logistics (25) ───
    "delivery":        {"name": "📦 Delivery Driver",   "base_pay": 25,   "min_level": 3,  "cooldown": 600,  "category": "transport", "description": "Deliver packages around the city."},
    "pilot":           {"name": "✈️ Pilot",             "base_pay": 250,  "min_level": 20, "cooldown": 7200, "category": "transport", "description": "Fly planes across the world."},
    "truck_driver":    {"name": "🚛 Truck Driver",      "base_pay": 50,   "min_level": 6,  "cooldown": 1200, "category": "transport", "description": "Haul cargo across long distances."},
    "taxi_driver":     {"name": "🚕 Taxi Driver",       "base_pay": 30,   "min_level": 4,  "cooldown": 900,  "category": "transport", "description": "Drive passengers around the city."},
    "bus_driver":      {"name": "🚌 Bus Driver",        "base_pay": 35,   "min_level": 4,  "cooldown": 900,  "category": "transport", "description": "Drive a city bus on a fixed route."},
    "train_driver":    {"name": "🚆 Train Driver",      "base_pay": 55,   "min_level": 7,  "cooldown": 1500, "category": "transport", "description": "Operate trains on regional routes."},
    "ship_captain":    {"name": "🚢 Ship Captain",      "base_pay": 180,  "min_level": 18, "cooldown": 3600, "category": "transport", "description": "Command cargo ships across oceans."},
    "forklift":        {"name": "🏗️ Forklift Operator", "base_pay": 38,   "min_level": 5,  "cooldown": 900,  "category": "transport", "description": "Move pallets in a warehouse."},
    "warehouse":       {"name": "📦 Warehouse Worker",  "base_pay": 28,   "min_level": 3,  "cooldown": 600,  "category": "transport", "description": "Pack, sort, and organize inventory."},
    "courier":         {"name": "🛵 Courier",           "base_pay": 32,   "min_level": 4,  "cooldown": 900,  "category": "transport", "description": "Deliver urgent documents on a scooter."},
    "ambulance_drv":   {"name": "🚑 Ambulance Driver",  "base_pay": 45,   "min_level": 5,  "cooldown": 1200, "category": "transport", "description": "Drive ambulances to emergencies."},
    "fire_truck_drv":  {"name": "🚒 Fire Truck Driver", "base_pay": 48,   "min_level": 6,  "cooldown": 1200, "category": "transport", "description": "Drive fire trucks to emergency scenes."},
    "subway_op":       {"name": "🚇 Subway Operator",   "base_pay": 42,   "min_level": 5,  "cooldown": 1200, "category": "transport", "description": "Drive underground subway trains."},
    "tram_driver":     {"name": "🚊 Tram Driver",       "base_pay": 36,   "min_level": 4,  "cooldown": 900,  "category": "transport", "description": "Drive street trams through the city."},
    "logistics_mgr":   {"name": "📋 Logistics Manager", "base_pay": 90,   "min_level": 11, "cooldown": 2400, "category": "transport", "description": "Coordinate supply chains and shipments."},
    "air_traffic":     {"name": "📡 Air Traffic Controller","base_pay": 120,"min_level": 14,"cooldown": 3000, "category": "transport", "description": "Guide planes safely through the skies."},
    "harbor_master":   {"name": "⚓ Harbor Master",      "base_pay": 100,  "min_level": 12, "cooldown": 2400, "category": "transport", "description": "Manage ship traffic at a busy port."},
    "cargo_pilot":     {"name": "✈️ Cargo Pilot",       "base_pay": 200,  "min_level": 18, "cooldown": 3600, "category": "transport", "description": "Fly cargo planes on overnight routes."},
    "helicopter_pilot":{"name": "🚁 Helicopter Pilot",  "base_pay": 160,  "min_level": 16, "cooldown": 3600, "category": "transport", "description": "Fly helicopters for tours, rescue, and transport."},
    "dispatch":        {"name": "📻 Dispatcher",        "base_pay": 52,   "min_level": 6,  "cooldown": 1200, "category": "transport", "description": "Coordinate drivers and routes from a control center."},
    "bike_courier":    {"name": "🚴 Bike Courier",      "base_pay": 22,   "min_level": 3,  "cooldown": 600,  "category": "transport", "description": "Deliver packages by bicycle in the city."},
    "chauffeur":       {"name": "🤵 Chauffeur",         "base_pay": 65,   "min_level": 8,  "cooldown": 1800, "category": "transport", "description": "Drive VIPs in luxury vehicles."},
    "tow_truck":       {"name": "🚛 Tow Truck Driver",  "base_pay": 40,   "min_level": 5,  "cooldown": 1200, "category": "transport", "description": "Tow broken-down vehicles to the shop."},
    "supply_chain":    {"name": "🔗 Supply Chain Analyst","base_pay": 110,"min_level": 13, "cooldown": 3000, "category": "transport", "description": "Optimize global supply chain operations."},
    "test_pilot":      {"name": "✈️ Test Pilot",        "base_pay": 300,  "min_level": 25, "cooldown": 7200, "category": "transport", "description": "Test experimental aircraft at supersonic speeds."},
}

# ═══════════════════════════════════════════════════════════════
# Subcategories — allows >25 jobs per category by splitting into
# navigable sub-groups. Each subcategory holds ≤25 jobs so Discord
# select menus never overflow.
# ═══════════════════════════════════════════════════════════════

JOB_SUBCATEGORIES = {
    "entry": {
        "street":   {"name": "🚶 Street Work",           "description": "Busking, begging, flyers, and street-level gigs."},
        "cleaning": {"name": "🧹 Cleaning & Maintenance","description": "Washing, cleaning, and tidying up."},
        "helper":   {"name": "🤝 Helper & Retail",       "description": "Helping out in shops, events, and odd jobs."},
    },
    "service": {
        "kitchen":    {"name": "👨‍🍳 Kitchen",            "description": "Cooking, prep, and culinary arts."},
        "beverage":   {"name": "☕ Beverages",            "description": "Coffee, tea, wine, and cocktails."},
        "front":      {"name": "🤵 Front of House",       "description": "Customer-facing service roles."},
        "specialty":  {"name": "🍫 Specialty Food",       "description": "Niche food crafts and expertise."},
        "management": {"name": "🏨 Hospitality Mgmt",     "description": "Manage venues and events."},
    },
    "trades": {
        "construction": {"name": "🏗️ Construction",       "description": "Build, paint, and finish structures."},
        "skilled":      {"name": "🔧 Skilled Trades",     "description": "Licensed trades: electrical, plumbing, HVAC."},
        "heavy":        {"name": "🚜 Heavy & Industrial", "description": "Heavy equipment and industrial work."},
        "outdoor":      {"name": "🌳 Outdoor",            "description": "Landscaping and outdoor labor."},
        "management":   {"name": "📋 Supervision",        "description": "Foremen, surveyors, and contractors."},
    },
    "medical": {
        "clinical": {"name": "🏥 Clinical",               "description": "Doctors, surgeons, and direct patient care."},
        "care":     {"name": "💊 Care & Practice",        "description": "Pharmacy, therapy, and specialized care."},
        "research": {"name": "🔬 Research & Science",     "description": "Lab work, research, and exploration."},
    },
    "tech": {
        "software":    {"name": "💻 Software Dev",        "description": "Programming, web, mobile, and games."},
        "data_ai":     {"name": "🤖 Data & AI",           "description": "Data science, ML, and blockchain."},
        "infra":       {"name": "⚙️ Infrastructure",      "description": "Sysadmin, DevOps, cloud, and networks."},
        "security":    {"name": "🔒 Security",            "description": "Cybersecurity and penetration testing."},
        "design_lead": {"name": "🎨 Design & Leadership", "description": "UX, product management, and C-level."},
    },
    "business": {
        "finance":    {"name": "💰 Finance",              "description": "Accounting, banking, and financial planning."},
        "management": {"name": "📋 Management",           "description": "HR, marketing, and operations."},
        "executive":  {"name": "👔 Executive",            "description": "C-suite and business owners."},
        "investing":  {"name": "📈 Investing",            "description": "Trading, VC, and hedge funds."},
        "services":   {"name": "🤝 Business Services",    "description": "Real estate, insurance, and negotiation."},
    },
    "creative": {
        "visual":     {"name": "🎨 Visual Arts",          "description": "Painting, photography, and crafts."},
        "performing": {"name": "🎭 Performing",           "description": "Acting, music, dance, and comedy."},
        "media_film": {"name": "🎬 Film & Media",         "description": "Filmmaking, animation, and production."},
        "design":     {"name": "🖌️ Design",               "description": "Fashion, interiors, and architecture."},
        "writing":    {"name": "✍️ Writing",              "description": "Novels, articles, and books."},
    },
    "transport": {
        "driving":    {"name": "🚗 Driving",              "description": "Taxis, buses, trucks, and trains."},
        "emergency":  {"name": "🚑 Emergency Transport",  "description": "Ambulance and fire truck driving."},
        "warehouse":  {"name": "📦 Warehouse",            "description": "Forklifts, packing, and dispatch."},
        "courier":    {"name": "🛵 Courier",              "description": "Bike and scooter delivery."},
        "aviation":   {"name": "✈️ Aviation",             "description": "Pilots and air traffic control."},
        "maritime":   {"name": "⚓ Maritime",             "description": "Ships and harbor management."},
        "management": {"name": "📋 Logistics Mgmt",       "description": "Supply chain and logistics leadership."},
    },
}

# Auto-assign subcategory to each job
_SUBCATEGORY_ASSIGNMENTS = {
    # ── Entry ──
    "beggar": "street", "busker": "street", "leafleter": "street", "shoe_shiner": "street",
    "sign_holder": "street", "balloon_seller": "street", "newspaper": "street", "survey_taker": "street",
    "window_washer": "cleaning", "janitor": "cleaning", "laundry": "cleaning", "car_wash": "cleaning",
    "litter_picker": "cleaning", "plant_waterer": "cleaning", "recycler": "cleaning",
    "dog_walker": "helper", "trolley": "helper", "moving_helper": "helper", "ticket_tearer": "helper",
    "ice_cream": "helper", "parking_attend": "helper", "garden_helper": "helper", "shelf_stocker": "helper",
    "food_sample": "helper", "cart_pusher": "helper",
    # ── Service ──
    "chef": "kitchen", "sushi_chef": "kitchen", "pastry_chef": "kitchen", "sous_chef": "kitchen",
    "private_chef": "kitchen", "caterer": "kitchen", "baker": "kitchen", "butcher": "kitchen",
    "barista": "beverage", "bartender": "beverage", "barista_master": "beverage", "sommelier": "beverage",
    "sommelier_master": "beverage", "mixologist": "beverage", "teasomm": "beverage",
    "waiter": "front", "fast_food": "front", "host": "front", "food_truck": "front",
    "chocolatier": "specialty", "nutritionist": "specialty", "food_critic": "specialty",
    "hotel_manager": "management", "event_planner": "management", "restaurateur": "management",
    # ── Trades ──
    "construction": "construction", "roofer": "construction", "painter": "construction",
    "mason": "construction", "tiler": "construction", "insulator": "construction",
    "scaffolder": "construction", "floor_layer": "construction",
    "mechanic": "skilled", "electrician": "skilled", "plumber": "skilled", "carpenter": "skilled",
    "welder": "skilled", "hvac": "skilled", "locksmith": "skilled", "glazier": "skilled",
    "heavy_equipment": "heavy", "steelworker": "heavy", "demolition": "heavy",
    "elevator_fix": "heavy", "solar_installer": "heavy",
    "landscaper": "outdoor",
    "foreman": "management", "surveyor": "management", "contractor": "management",
    # ── Medical ──
    "doctor": "clinical", "nurse": "clinical", "paramedic": "clinical", "surgeon": "clinical",
    "cardiologist": "clinical", "neurosurgeon": "clinical", "pediatrician": "clinical", "dentist": "clinical",
    "pharmacist": "care", "vet": "care", "therapist": "care", "optometrist": "care",
    "physical_ther": "care", "radiologist": "care",
    "lab_tech": "research", "research_sci": "research", "biologist": "research", "chemist": "research",
    "physicist": "research", "astronomer": "research", "geneticist": "research", "med_researcher": "research",
    "epidemiologist": "research", "toxicologist": "research", "astronaut": "research",
    # ── Tech ──
    "programmer": "software", "web_dev": "software", "frontend_dev": "software", "backend_dev": "software",
    "mobile_dev": "software", "game_dev": "software", "qa_tester": "software", "tech_writer": "software",
    "data_analyst": "data_ai", "data_scientist": "data_ai", "db_admin": "data_ai",
    "ai_engineer": "data_ai", "ml_engineer": "data_ai", "blockchain_dev": "data_ai",
    "sysadmin": "infra", "devops": "infra", "cloud_arch": "infra", "network_eng": "infra", "it_support": "infra",
    "security_analyst": "security", "pentester": "security", "hacker": "security",
    "ux_designer": "design_lead", "product_manager": "design_lead", "cto": "design_lead",
    # ── Business ──
    "bank_teller": "finance", "accountant": "finance", "bookkeeper": "finance", "auditor": "finance",
    "tax_prep": "finance", "loan_officer": "finance", "financial_adv": "finance", "stockbroker": "finance",
    "manager": "management", "hr_specialist": "management", "marketing": "management",
    "consultant": "management", "sales_rep": "management",
    "ceo": "executive", "cfo": "executive", "coo": "executive", "entrepreneur": "executive", "magnate": "executive",
    "investment_bank": "investing", "venture_cap": "investing", "hedge_fund": "investing", "trader": "investing",
    "real_estate": "services", "insurance": "services", "negotiator": "services",
    # ── Creative ──
    "artist": "visual", "photographer": "visual", "graphic_design": "visual",
    "sculptor": "visual", "potter": "visual", "jeweler": "visual",
    "actor": "performing", "dancer": "performing", "comedian": "performing", "stunt_double": "performing",
    "voice_actor": "performing", "musician": "performing", "dj": "performing", "maestro": "performing",
    "filmmaker": "media_film", "director": "media_film", "animator": "media_film", "producer": "media_film",
    "fashion_design": "design", "interior_design": "design", "architect": "design",
    "tattoo_artist": "design", "makeup_artist": "design",
    "writer": "writing", "novelist": "writing",
    # ── Transport ──
    "delivery": "driving", "taxi_driver": "driving", "bus_driver": "driving", "truck_driver": "driving",
    "train_driver": "driving", "tram_driver": "driving", "subway_op": "driving", "chauffeur": "driving",
    "ambulance_drv": "emergency", "fire_truck_drv": "emergency",
    "forklift": "warehouse", "warehouse": "warehouse", "dispatch": "warehouse",
    "courier": "courier", "bike_courier": "courier", "tow_truck": "courier",
    "pilot": "aviation", "cargo_pilot": "aviation", "helicopter_pilot": "aviation",
    "test_pilot": "aviation", "air_traffic": "aviation",
    "ship_captain": "maritime", "harbor_master": "maritime",
    "logistics_mgr": "management", "supply_chain": "management",
}

for _jid, _sub in _SUBCATEGORY_ASSIGNMENTS.items():
    if _jid in JOBS:
        JOBS[_jid]["subcategory"] = _sub


def get_jobs_by_category(category: str, subcategory: str = None) -> dict:
    """Get all jobs in a category, optionally filtered by subcategory."""
    result = {}
    for jid, job in JOBS.items():
        if job.get("category") != category:
            continue
        if subcategory and job.get("subcategory") != subcategory:
            continue
        result[jid] = job
    return result


def get_subcategories(category: str) -> dict:
    """Get subcategories for a category, or empty dict if none."""
    return JOB_SUBCATEGORIES.get(category, {})
