LOCATIONS = {
    "market": {
        "name": "🏪 Town Market", "emoji": "🏪",
        "description": "A bustling marketplace filled with merchants and goods.",
        "activities": ["trade", "buy", "sell", "npc"],
        "npcs": ["merchant_sam", "chef_marie", "blacksmith_gus"],
        "encounter_chance": 0.3,
        "loot_table": ["cloth", "herbs", "metal_scrap", "stone"],
        "danger": 0.0,
    },
    "docks": {
        "name": "⚓ The Docks", "emoji": "⚓",
        "description": "Weathered piers and the smell of salt water. Perfect for fishing.",
        "activities": ["fish", "npc", "explore"],
        "npcs": ["fisherman_joe"],
        "encounter_chance": 0.25,
        "loot_table": ["fish", "cloth", "metal_scrap"],
        "danger": 0.05,
    },
    "mines": {
        "name": "⛏️ The Mines", "emoji": "⛏️",
        "description": "Dark tunnels stretching deep underground. Rich with ore.",
        "activities": ["mine", "npc", "explore"],
        "npcs": ["miner_kate"],
        "encounter_chance": 0.35,
        "loot_table": ["stone", "metal_scrap", "gems", "clay"],
        "danger": 0.15,
    },
    "forest": {
        "name": "🌲 Whispering Forest", "emoji": "🌲",
        "description": "Ancient trees and hidden clearings. Full of life and mystery.",
        "activities": ["forage", "chop", "explore", "npc"],
        "npcs": ["mystic_elara", "ranger_tom"],
        "encounter_chance": 0.4,
        "loot_table": ["wood", "herbs", "stone", "cloth"],
        "danger": 0.10,
    },
    "alley": {
        "name": "🏚️ Back Alleys", "emoji": "🏚️",
        "description": "Narrow, shadowy passages. Not a place for the unwary.",
        "activities": ["explore", "crime", "npc"],
        "npcs": ["drifter_vex"],
        "encounter_chance": 0.45,
        "loot_table": ["metal_scrap", "cloth", "stone"],
        "danger": 0.20,
    },
    "beach": {
        "name": "🌅 Sunset Beach", "emoji": "🌅",
        "description": "Golden sands and rolling waves. Relaxing, but watch the tide.",
        "activities": ["fish", "forage", "explore"],
        "npcs": [],
        "encounter_chance": 0.2,
        "loot_table": ["stone", "clay", "fish", "cloth"],
        "danger": 0.05,
    },
    "ruins": {
        "name": "🏛️ Ancient Ruins", "emoji": "🏛️",
        "description": "Crumbling stone structures from a forgotten age. Secrets lie within.",
        "activities": ["explore", "dig", "mine"],
        "npcs": [],
        "encounter_chance": 0.5,
        "loot_table": ["stone", "gems", "metal_scrap", "clay"],
        "danger": 0.25,
    },
    "mountains": {
        "name": "⛰️ Misty Mountains", "emoji": "⛰️",
        "description": "Towering peaks shrouded in fog. The brave are rewarded here.",
        "activities": ["mine", "explore", "chop"],
        "npcs": [],
        "encounter_chance": 0.35,
        "loot_table": ["stone", "gems", "wood", "metal_scrap"],
        "danger": 0.20,
    },
    "lake": {
        "name": "🏞️ Crystal Lake", "emoji": "🏞️",
        "description": "Clear, still waters surrounded by wildflowers. A peaceful spot.",
        "activities": ["fish", "forage", "explore"],
        "npcs": [],
        "encounter_chance": 0.15,
        "loot_table": ["fish", "herbs", "wood", "clay"],
        "danger": 0.03,
    },
    "canyon": {
        "name": "🏜️ Red Canyon", "emoji": "🏜️",
        "description": "Sweeping rock formations and narrow passes. Treasure hunters' paradise.",
        "activities": ["explore", "dig", "mine"],
        "npcs": [],
        "encounter_chance": 0.4,
        "loot_table": ["stone", "gems", "metal_scrap", "clay"],
        "danger": 0.18,
    },
}
