NARRATIVE_TEMPLATES = {
    "explore": {
        "intro": [
            "You venture into {location}, {mood}.",
            "Your footsteps echo through {location} as you look around, {mood}.",
            "The path leads you to {location}. You feel {mood}.",
            "{location} stretches before you, {mood}.",
            "You push forward into {location}, {mood}.",
            "The air shifts as you enter {location}, {mood}.",
            "{location} looms ahead. You proceed, {mood}.",
            "Step by step, you make your way into {location}, {mood}.",
            "You find yourself at {location}, {mood}.",
            "The world narrows to {location} as you approach, {mood}.",
            "A familiar turn brings you to {location}, {mood}.",
            "You slip quietly into {location}, {mood}.",
            "{location} opens up before you. You pause, {mood}.",
            "With a deep breath, you step into {location}, {mood}.",
            "The entrance to {location} is unremarkable, but you proceed, {mood}.",
            "You cross the threshold into {location}, {mood}.",
        ],
        "locations": [
            "an abandoned warehouse", "a dense forest", "a crumbling alleyway",
            "the old docks", "a forgotten park", "the city outskirts",
            "a mysterious cave", "the rooftops", "an underground tunnel",
            "a quiet meadow", "the ruins of an old building", "a narrow canyon",
            "the beach at low tide", "a foggy marshland", "an overgrown garden",
            "the train yard", "a dried riverbed", "the edge of a cliff",
            "a sunlit clearing", "a flooded basement", "a winding mountain trail",
            "a derelict factory floor", "a hidden grove", "a storm drain",
        ],
        "moods": [
            "unsure what to expect", "with a sense of adventure",
            "feeling cautious", "heart pounding with excitement",
            "trying to stay quiet", "scanning for danger",
            "ready for anything", "with weary determination",
            "hoping for something good", "dreading what you might find",
            "running on adrenaline", "curious despite yourself",
            "moving on instinct", "with practiced calm",
            "half-expecting trouble", "driven by curiosity",
        ],
        "find_item": [
            "Something catches your eye — a {item}!",
            "Tucked away in a corner, you spot a {item}.",
            "Half-buried in debris, you find a {item}.",
            "Glinting in the light, you discover a {item}.",
            "You almost miss it, but there's a {item} here.",
            "A flash of color reveals a {item} nestled in the dust.",
            "Under a pile of rubble, your fingers close around a {item}.",
            "You weren't looking for it, but a {item} was looking for you.",
            "Peeking out from behind a broken beam: a {item}.",
            "You brush away some dirt and uncover a {item}.",
            "A {item} sits on a ledge, as if someone left it for you.",
            "You reach into a crevice and pull out a {item}.",
        ],
        "find_nothing": [
            "You search around but find nothing of value.",
            "The area is picked clean. Nothing here.",
            "Your search comes up empty.",
            "You spend time looking but it's a dead end.",
            "Someone's been here before you. The place is stripped bare.",
            "You turn over every stone — metaphorically and literally — but find nothing.",
            "Not a single thing worth taking. Disappointing.",
            "The area yields nothing but dust and disappointment.",
            "You comb through the debris, but luck isn't with you today.",
            "Whatever was here is long gone. You're too late.",
            "Empty. Barren. A waste of time.",
            "You check every corner, every shadow. Nothing. Absolutely nothing.",
        ],
        "encounter_npc": [
            "A {npc} appears from the shadows!",
            "You come face to face with a {npc}.",
            "A {npc} blocks your path.",
            "You hear a noise — it's a {npc}.",
            "A {npc} steps out from behind cover, startling you.",
            "You nearly bump into a {npc} rounding a corner.",
            "A {npc} is sitting nearby, watching you approach.",
            "You notice a {npc} lurking at the edge of your vision.",
            "A {npc} calls out to you from across the way.",
            "You stumble upon a {npc} who seems to have been waiting.",
            "A {npc} emerges from the gloom ahead.",
            "You lock eyes with a {npc} across the empty space.",
        ],
        "npcs": [
            "wandering trader", "suspicious stranger", "friendly hiker",
            "lost tourist", "scruffy scavenger", "nervous courier",
            "old fisherman", "mysterious hooded figure", "panicked runner",
            "calm meditator", "excited child", "weary traveler",
            "grizzled prospector", "jittery thief", "whistling bard",
            "hooded courier",
        ],
        "npc_outcomes": {
            "wandering trader": ["offers to trade", "gives you a tip", "sells you something", "ignores you", "shows you a rare item", "warns you about a scam"],
            "suspicious stranger": ["challenges you", "offers a shady deal", "warns you of danger", "disappears", "sizes you up silently", "slips you a note and leaves"],
            "friendly hiker": ["shares supplies", "points out a landmark", "gives directions", "offers company", "shares a trail tip", "warns about a blocked path"],
            "lost tourist": ["asks for directions", "offers a reward for help", "looks confused", "drops something", "shows you a map", "thanks you profusely and leaves"],
            "scruffy scavenger": ["competes for loot", "offers to split finds", "tries to scam you", "shares gossip", "grumbles and moves on", "trades you something unexpected"],
            "nervous courier": ["drops a package", "asks you to deliver something", "rushes past", "pays you to stay quiet", "glances over their shoulder and hurries off", "hands you a letter and vanishes"],
            "old fisherman": ["shares fishing tips", "gives you bait", "tells a story", "offers a spare fish", "mumbles about the one that got away", "points you toward a better spot"],
            "mysterious hooded figure": ["offers a quest", "gives a cryptic warning", "vanishes mysteriously", "sells a rare item", "speaks in riddles and departs", "watches you in silence before fading away"],
            "panicked runner": ["warns of danger ahead", "drops coins while running", "asks for help", "knocks you over", "shouts a warning and disappears", "grabs your arm and pulls you back"],
            "calm meditator": ["teaches you breathing", "gives you peace of mind", "offers wisdom", "shares energy", "invites you to sit a while", "imparts a single word and smiles"],
            "excited child": ["shows you a hiding spot", "gives you a trinket", "points at something shiny", "giggles and runs off", "asks you a rapid-fire question", "leads you to a secret spot"],
            "weary traveler": ["shares a meal", "tells of distant lands", "offers to rest together", "trades stories", "warns you about the road ahead", "gives you a token for luck"],
            "grizzled prospector": ["shows you a nugget", "grumbles about claim jumpers", "points you toward a vein", "shares a mining secret", "offers to split a claim", "tells you to turn back"],
            "jittery thief": ["tries to pickpocket you", "bumps into you and apologizes", "flees at the sight of you", "drops stolen goods", "offers to sell you something hot", "whispers a warning about the guards"],
            "whistling bard": ["plays you a tune", "sings a bawdy song", "tells a joke for coins", "shares a rumor", "dedicates a song to you", "hums and wanders off"],
            "hooded courier": ["hands you a sealed letter", "asks you to deliver a package", "pays you to hold something", "mistransmits an address and leaves", "drops a map and keeps walking", "nods and disappears into the crowd"],
        },
        "danger": [
            "You slip and twist your ankle! -{hp} HP",
            "A wild animal lunges at you! -{hp} HP",
            "You fall into a hidden hole! -{hp} HP",
            "Debris falls on you! -{hp} HP",
            "You cut yourself on sharp metal! -{hp} HP",
            "A rotting floorboard gives way beneath you! -{hp} HP",
            "Something stings your arm — a wasp nest! -{hp} HP",
            "You walk straight into a low-hanging beam! -{hp} HP",
            "A loose stone tumbles down and hits your shoulder! -{hp} HP",
            "You misjudge a jump and land hard! -{hp} HP",
            "A rusted nail catches your leg! -{hp} HP",
            "You trigger a small rockslide! -{hp} HP",
        ],
        "reward": [
            "You feel accomplished! +{xp} XP",
            "Your efforts pay off! +{xp} XP",
            "You learned something new! +{xp} XP",
            "A successful expedition! +{xp} XP",
            "You're getting better at this! +{xp} XP",
            "Experience gained — every trip teaches you something. +{xp} XP",
            "You feel wiser for the journey. +{xp} XP",
            "A rewarding venture! +{xp} XP",
            "You push your limits and grow. +{xp} XP",
            "The world rewards the bold. +{xp} XP",
            "You feel the confidence of experience. +{xp} XP",
            "Another step, another lesson. +{xp} XP",
        ],
    },
    "fish": {
        "cast": [
            "You cast your line into the {spot}, waiting patiently...",
            "Your hook plops into the {spot}. You wait...",
            "You flick your rod and the line sails into the {spot}.",
            "With a practiced motion, you send your line sailing across the {spot}.",
            "You swing your rod and the bait lands with a soft splash in the {spot}.",
            "The line whispers through the air before settling on the {spot}.",
            "You settle into position and cast into the {spot}, watching the ripples spread.",
            "Your lure arcs gracefully before disappearing beneath the surface of the {spot}.",
            "You let out a breath and cast — the line cuts the air and finds the {spot}.",
            "The rod bends slightly as you whip the line into the {spot}, settling in to wait.",
            "You adjust your stance and send the hook flying into the {spot}.",
            "A smooth overhand cast drops your bait right where you want it in the {spot}.",
        ],
        "spots": ["calm waters", "rushing river", "murky pond", "deep lake", "rocky shoreline", "gentle stream", "tide pool", "misty inlet", "reedy marsh", "swift current", "still cove", "moonlit shallows"],
        "catch": [
            "You feel a tug! You reel in a {fish}!",
            "Something's biting! You pull up a {fish}!",
            "Your rod bends — got one! A {fish}!",
            "A strong pull! You wrestle in a {fish}!",
            "The line goes taut and you haul up a {fish}!",
            "A sharp jerk — you set the hook and reel in a {fish}!",
            "Your reel screams as something fights back — a {fish}!",
            "You feel the weight on the line and pull hard — a {fish} comes up!",
            "The rod doubles over and you crank the reel — a {fish} surfaces!",
            "A sudden strike! You react fast and land a {fish}!",
            "The tip of your rod dips and you yank — a {fish} on the line!",
            "You feel the familiar vibration through the rod — a {fish}!",
        ],
        "fish_types": [
            ("tiny minnow", 5), ("small perch", 15), ("decent bass", 30),
            ("fat catfish", 50), ("shiny trout", 40), ("rare salmon", 80),
            ("golden koi", 150), ("ancient carp", 100), ("electric eel", 60),
            ("mysterious boot", 2), ("waterlogged wallet", 25), ("old bottle with a note", 10),
        ],
        "nothing": [
            "Nothing bites. You wait...",
            "The line sits still. No luck.",
            "Hours pass with no catch.",
            "A fish nibbles but gets away!",
            "The water is quiet. Not even a ripple.",
            "Your bait sits untouched. The fish aren't interested today.",
            "You feel a tiny tug — but it's just the current. Nothing.",
            "You reel in to check your bait — it's gone, but no fish. Sneaky.",
            "The line goes slack. Whatever was there got away.",
            "You wait and wait, but the water gives up nothing.",
            "A breeze ripples the surface, but no fish show themselves.",
            "You pack up, empty-handed. The fish won today.",
        ],
    },
    "mine": {
        "swing": [
            "You swing your pickaxe at the {vein}, chips flying!",
            "Your pickaxe strikes the {vein} with a clang!",
            "You chip away at the {vein}, sweat on your brow.",
            "You bring the pickaxe down hard on the {vein}, dust billowing.",
            "Your swing connects with the {vein} — a satisfying crack echoes.",
            "You jab the pick into the {vein} and pry, rock groaning.",
            "Overhead swing — the pickaxe bites deep into the {vein}.",
            "You pause, adjust your grip, and strike the {vein} with all your weight.",
            "The pickaxe rings out as it crashes into the {vein}.",
            "You swing again and again at the {vein}, rhythm taking over.",
            "A glancing blow off the {vein} — you adjust and swing harder.",
            "You twist the pickaxe in the {vein}, levering a chunk loose.",
        ],
        "veins": ["rocky wall", "dark tunnel", "glittering seam", "cave wall", "underground deposit", "ancient stone", "cracked boulder", "vein of quartz", "shale formation", "volcanic rock", "mineral vein", "collapsed corridor"],
        "find": [
            "You extract a {ore}!",
            "A {ore} tumbles out of the rubble!",
            "You uncover a {ore}!",
            "Hidden in the stone, you find a {ore}!",
            "Your pickaxe cracks open a pocket — a {ore} inside!",
            "You brush away the dust and a {ore} gleams back at you.",
            "A chunk of {ore} breaks free and rolls to your feet!",
            "You pry loose a {ore} from the surrounding rock.",
            "Something catches the light — a {ore}, wedged in the crevice!",
            "The rock splits cleanly, revealing a {ore} within.",
            "You scoop up a {ore} from the debris at the base of the wall.",
            "A {ore} falls out as the wall crumbles under your swing!",
        ],
        "ore_types": [
            ("chunk of coal", 10), ("piece of iron", 25), ("hunk of copper", 20),
            ("chunk of silver", 60), ("nugget of gold", 120), ("raw diamond", 300),
            ("shiny gemstone", 80), ("rare crystal", 200), ("chunk of obsidian", 40),
            ("worthless rock", 1), ("old coin", 15), ("fossil", 50),
        ],
        "cave_in": [
            "Rocks shift dangerously above you!",
            "You hear a rumble — the cave is unstable!",
            "Dust falls from the ceiling as the ground shakes!",
            "A crack spreads across the ceiling — time to move!",
            "The support beam groans loudly. You should leave. Now.",
            "Small stones cascade from above — a warning sign.",
            "The floor trembles and the walls shudder. Cave-in imminent!",
            "A deep groan from the earth itself — the tunnel is collapsing!",
        ],
    },
    "random_event": {
        "events": [
            {"texts": [
                "A street performer plays music nearby. You toss them some coins. -{coins} coins, +{xp} XP",
                "A busker strums a guitar on the corner. You appreciate the tune and drop some change. -{coins} coins, +{xp} XP",
                "Someone is juggling fire down the street! You tip them for the show. -{coins} coins, +{xp} XP",
                "A musician plays a haunting melody on a violin. You stop to listen and leave a few coins. -{coins} coins, +{xp} XP",
            ], "coins": (5, 30), "xp": (5, 15), "weight": 10},
            {"texts": [
                "You find a wallet on the ground! +{coins} coins",
                "There's a dropped purse leaning against a lamppost. Score! +{coins} coins",
                "You spot a crumpled bill on the sidewalk. Then another. And another! +{coins} coins",
                "Someone left a money clip on a park bench. Their loss, your gain. +{coins} coins",
            ], "coins": (20, 100), "xp": 0, "weight": 8},
            {"texts": [
                "A sudden gust of wind blows dust in your eyes. -{hp} HP",
                "The wind kicks up a cloud of grit right into your face. Ouch! -{hp} HP",
                "A blast of air sends sand into your eyes. You stumble, rubbing them. -{hp} HP",
                "Debris whips past in a gust, scratching your cheek. -{hp} HP",
            ], "coins": 0, "hp": (1, 5), "weight": 7},
            {"texts": [
                "You witness a random act of kindness. You feel inspired! +{xp} XP",
                "You watch a stranger help someone carry their groceries. Heartwarming! +{xp} XP",
                "Someone returns a lost dog to its owner right in front of you. You feel uplifted. +{xp} XP",
                "A teenager helps an old man up after he trips. You feel a warm glow. +{xp} XP",
            ], "coins": 0, "xp": (10, 25), "weight": 8},
            {"texts": [
                "A stray cat follows you for a while. You feel less lonely. +{hygiene} hygiene",
                "A scruffy dog trots alongside you, tail wagging. The company lifts your spirits. +{hygiene} hygiene",
                "A pigeon waddles after you for half a block. You feel oddly comforted. +{hygiene} hygiene",
                "A friendly tabby rubs against your leg and purrs. You feel a bit better. +{hygiene} hygiene",
            ], "coins": 0, "hygiene": (3, 8), "weight": 6},
            {"texts": [
                "You stumble on a curb and scrape your knee. -{hp} HP",
                "You trip over an uneven paving stone and skin your palm. -{hp} HP",
                "Your foot catches on a crack in the sidewalk. You go down hard. -{hp} HP",
                "You misstep off a curb and twist your ankle slightly. -{hp} HP",
            ], "coins": 0, "hp": (2, 8), "weight": 7},
            {"texts": [
                "Someone hands you a flyer. On the back is a coupon! +{coins} coins next purchase",
                "A promoter shoves a leaflet into your hand. Hey — there's a discount code on the back! +{coins} coins",
                "You almost throw away a junk mail flyer, but spot a voucher tucked inside. +{coins} coins",
                "A coupon falls out of a newspaper someone left on a bench. Nice! +{coins} coins",
            ], "coins": (10, 50), "xp": 0, "weight": 6},
            {"texts": [
                "You help an elderly person cross the street. +{xp} XP, +{hygiene} hygiene",
                "You carry a heavy box up the stairs for a neighbor. They thank you profusely. +{xp} XP, +{hygiene} hygiene",
                "You return a dropped phone to its owner. They're so grateful! +{xp} XP, +{hygiene} hygiene",
                "You help a parent wrangle their toddler back into a stroller. They look at you like you're a saint. +{xp} XP, +{hygiene} hygiene",
            ], "coins": 0, "xp": (5, 20), "hygiene": (2, 5), "weight": 7},
            {"texts": [
                "A bird drops something on your head. Gross! -{hygiene} hygiene",
                "A pigeon bombs you from above. Direct hit. Disgusting. -{hygiene} hygiene",
                "A flock of birds flushes from a tree above you. Not all of it is leaves. -{hygiene} hygiene",
                "Something wet and warm lands on your shoulder. You don't want to look. -{hygiene} hygiene",
            ], "coins": 0, "hygiene": (5, 15), "weight": 5},
            {"texts": [
                "You find loose change in a vending machine slot! +{coins} coins",
                "There are coins sitting in the return slot of a payphone! +{coins} coins",
                "You check under a bench cushion and find a few coins. +{coins} coins",
                "Someone left change in the coin tray of a parking meter! +{coins} coins",
            ], "coins": (2, 15), "xp": 0, "weight": 9},
            {"texts": [
                "A flash mob appears and dances! You join in. +{energy} energy, +{xp} XP",
                "A group of people suddenly start singing in harmony. You clap along, energized. +{energy} energy, +{xp} XP",
                "A drum circle forms in the square. You tap your feet and feel the rhythm. +{energy} energy, +{xp} XP",
                "Someone starts a spontaneous dance-off. You throw down a move. The crowd cheers! +{energy} energy, +{xp} XP",
            ], "coins": 0, "energy": (5, 15), "xp": (5, 15), "weight": 4},
            {"texts": [
                "You get caught in a sudden downpour. -{hygiene} hygiene",
                "Rain comes out of nowhere. You're soaked to the bone in seconds. -{hygiene} hygiene",
                "A cloudburst dumps on you with no warning. You're drenched. -{hygiene} hygiene",
                "The sky opens up and you have no umbrella. Miserable. -{hygiene} hygiene",
            ], "coins": 0, "hygiene": (10, 20), "weight": 5},
            {"texts": [
                "A street vendor gives you a free sample! +{hunger} hunger",
                "A bakery is handing out bite-sized portions of a new pastry. Delicious! +{hunger} hunger",
                "Someone at a food stall offers you a taste of their special sauce. Tasty! +{hunger} hunger",
                "A food truck guy slides you a free dumpling. You eat it in one bite. +{hunger} hunger",
            ], "coins": 0, "hunger": (5, 15), "weight": 6},
            {"texts": [
                "You find a four-leaf clover! +{xp} XP, feeling lucky!",
                "You spot a four-leaf clover in a patch of weeds. A good omen! +{xp} XP",
                "A glint of green catches your eye — a four-leaf clover! Fortune smiles on you. +{xp} XP",
                "You kneel to tie your shoe and notice a four-leaf clover right at your feet. +{xp} XP",
            ], "coins": 0, "xp": (10, 20), "weight": 3},
            {"texts": [
                "Your phone buzzes — it's a scam call. Annoying! -{energy} energy",
                "A telemarketer calls you for the third time today. You hang up, frustrated. -{energy} energy",
                "You get a spam text that wakes you from a daydream. Irritating. -{energy} energy",
                "Your phone rings — it's an automated message about your car's extended warranty. Ugh. -{energy} energy",
            ], "coins": 0, "energy": (2, 5), "weight": 5},
            {"texts": [
                "You see a shooting star! You make a wish. +{xp} XP",
                "A brilliant meteor streaks across the sky. You close your eyes and wish. +{xp} XP",
                "The night sky lights up for a split second — a falling star! You wish quickly. +{xp} XP",
                "You catch a meteor blazing across the horizon. Magical. +{xp} XP",
            ], "coins": 0, "xp": (15, 30), "weight": 2},
            {"texts": [
                "A kid bumps into you and apologizes, handing you a coin. +{coins} coins",
                "A running child collides with your leg, says sorry, and gives you a coin for the trouble. +{coins} coins",
                "A little kid trips over your foot. They hand you a coin before running off. +{coins} coins",
                "A child accidentally kicks a ball at you. They apologize and give you a coin. +{coins} coins",
            ], "coins": (1, 10), "xp": 0, "weight": 5},
            {"texts": [
                "You step in a puddle. Your socks are wet. -{energy} energy, -{hygiene} hygiene",
                "You walk straight into a deep puddle. Water soaks through your shoes instantly. -{energy} energy, -{hygiene} hygiene",
                "A car speeds through a puddle and splashes you head to toe. The worst. -{energy} energy, -{hygiene} hygiene",
                "You don't notice the puddle until it's too late. Cold water seeps in. -{energy} energy, -{hygiene} hygiene",
            ], "coins": 0, "energy": (3, 8), "hygiene": (3, 8), "weight": 5},
        ],
    },
}
