NPCS = {
    "merchant_sam": {
        "name": "Sam the Merchant", "emoji": "🧑‍💼",
        "location": "market", "personality": "shrewd",
        "greeting": [
            "Ah, a customer! Step right up.",
            "Well now, a fresh face with a full purse, I hope!",
            "Look who it is — come, come, let me show you something special.",
            "You caught me at the perfect time. Business is just getting interesting.",
            "Welcome, welcome! Best deals in town!",
            "Step right in, friend! You won't find better prices anywhere, I promise.",
            "Ah, another savvy shopper. I can always tell. Come see what I've got.",
            "Good to see you! Today's the day for bargains, I can feel it.",
            "You look like someone who appreciates quality.",
            "Sharp eye you've got there. Let me show you the good stuff.",
            "I can tell — you're not here for the cheap goods, are you? Right this way.",
            "You have the look of someone who knows value when they see it. Step inside.",
        ],
        "dialogue": [
            "Business has been good lately. The weather helps.",
            "Trade's been steady this season. Can't complain, won't complain.",
            "The market's been kind to me lately. Long may it last.",
            "Good week for business. People are spending, the weather's fair — perfect storm for profits.",
            "I once found a legendary gem in these parts. Never again, though.",
            "Years ago I pulled a gem so bright it hurt the eyes. Sold it and swore off mining for good.",
            "There's a vein somewhere out there with my name on it — but I'm a merchant now, not a miner.",
            "Found a legendary stone once. The man I sold it to disappeared a week later. Coincidence? Maybe.",
            "You hear about the storm last night? Wiped out half my stock.",
            "That storm was brutal — lost half my inventory to water damage. Rebuilding though.",
            "The weather's been murder on merchandise. I lost a whole crate to the last downpour.",
            "Storm took out half my tent last night. If you've got cloth, I'm buying.",
            "I'll give you a fair price — but only because I like you.",
            "For you? A special rate. Don't tell the others.",
            "I'm feeling generous today. Let's just say I won't haggle as hard.",
            "You drive a hard bargain, but I respect that. Let's make it work.",
        ],
        "trades": [
            {"give": "wood", "give_qty": 3, "receive": "herbs", "receive_qty": 1},
            {"give": "stone", "give_qty": 5, "receive": "cloth", "receive_qty": 2},
            {"give": "metal_scrap", "give_qty": 2, "receive": "fish", "receive_qty": 1},
        ],
        "quest": {"type": "deliver", "item": "cloth", "qty": 5, "reward": 200, "xp": 50, "desc": "Sam needs 5 cloth for a new tent"},
    },
    "fisherman_joe": {
        "name": "Old Joe", "emoji": "🧓",
        "location": "docks", "personality": "wise",
        "greeting": [
            "Ah, another young angler.",
            "Well, well — another soul drawn to the water. Pull up a crate and sit.",
            "Fresh face at the docks. Come to try your luck, have you?",
            "A new angler! The sea always welcomes the patient ones. Sit a spell.",
            "Sit a while. The fish aren't going anywhere.",
            "No rush out here. The tide waits for no one, but it doesn't chase anyone either.",
            "Take a load off. Fishing teaches you that waiting is half the catch.",
            "Rest your legs. The fish will bite when they're good and ready.",
            "I've been fishing these waters for 40 years.",
            "Four decades on these docks. Every ripple tells me a story.",
            "Been here since before you were born, I'd wager. The water and I are old friends.",
            "Forty years of casting and reeling. I know every current like the back of my hand.",
        ],
        "dialogue": [
            "The big ones come out at dawn, you know.",
            "First light is when the giants feed. Be on the water before the sun crests.",
            "Dawn fishing — that's the secret. The big ones don't like the crowds.",
            "You want the trophy fish? Get here before sunrise. They sleep when the sun's up.",
            "Stormy weather scares the fish away. Try again when it clears.",
            "Fish can feel the pressure drop before a storm. They head deep and stay there.",
            "No use casting in a tempest. Give it a day after the weather breaks, then try again.",
            "The fish go quiet when the sky turns. Patience — wait for clear skies.",
            "I once caught a golden koi that weighed 20 pounds. Let it go, though.",
            "A golden koi — 20 pounds if it was an ounce. Most beautiful thing I've ever pulled from the water. Threw it back.",
            "There was a koi so gold it looked like a bar of bullion. Biggest catch of my life. I let her swim.",
            "Caught a golden koi once that could've fed a family for a week. Some things are too beautiful to sell.",
            "You using the right bait? Try near the rocks.",
            "Bait matters more than luck. And the rocks — that's where the good ones hide.",
            "Change your bait, change your luck. And cast by the rocks, not the open water.",
            "The fish by the rocks are bigger and hungrier. Use live bait if you've got it.",
            "There's a legend about a monster fish in the deep lake. Never seen it myself.",
            "They say something enormous lives in the deep lake. Old as the hills. I've never seen it, but I've felt it.",
            "The deep lake has a creature in it — or so the stories say. I've fished there a hundred times and never caught more than a shadow.",
            "Monster fish in the deep lake? Maybe. The water down there goes darker than you'd expect. I don't go anymore.",
        ],
        "trades": [
            {"give": "fish", "give_qty": 3, "receive": "cooked_fish_item", "receive_qty": 1},
            {"give": "fish", "give_qty": 5, "receive": "fishing_lure", "receive_qty": 1},
        ],
        "quest": {"type": "catch", "item": "fish", "qty": 10, "reward": 300, "xp": 80, "desc": "Joe wants you to catch 10 fish to prove you're serious"},
    },
    "miner_kate": {
        "name": "Kate the Miner", "emoji": "👩‍🏭",
        "location": "mines", "personality": "tough",
        "greeting": [
            "Watch your step down here.",
            "Mind the loose rocks. One wrong step and you're at the bottom.",
            "Eyes on the ground. The mine doesn't forgive clumsy feet.",
            "Careful — the floor's uneven. I've seen too many beginners twist an ankle on the first day.",
            "New to mining? Stick close.",
            "Fresh pickaxe, eh? Stay near me until you learn the tunnels.",
            "First time underground? Don't wander. The dark plays tricks on newcomers.",
            "Rookie? Good. Stick to my heels and I'll keep you alive long enough to learn.",
            "The deep tunnels aren't for the faint-hearted.",
            "Below the third level, the air gets thin and the tunnels get narrow. Not everyone can handle it.",
            "The deep shafts test your nerve. If you're the type to panic, stay up top.",
            "Down in the dark, it's just you and the rock. Some people crack. Some people find gold.",
        ],
        "dialogue": [
            "I found a diamond last week. Sold it for a fortune.",
            "Pulled a diamond out of tunnel 4 last week. Biggest I've seen in years. Retire-on-that kind of money.",
            "Last week — diamond, clean as a tear. Sold it before the dust settled.",
            "Found a diamond seven days ago. The buyer nearly fell over when he saw the size of it.",
            "The cave-ins are getting worse lately. Be careful.",
            "Cave-ins are happening more often. The supports are old. Don't linger in the lower tunnels.",
            "Ground's been unstable. I lost a good tunnel last month. Keep your ears open for rumbling.",
            "The walls are shifting more than they used to. Always have an exit plan down here.",
            "You hear that rumbling? Could be trouble. Could be treasure.",
            "That rumble — could be the mountain settling, could be a vein opening up. Only one way to find out.",
            "Hear that? Either the tunnel's about to collapse or we're sitting on top of something big.",
            "Rumbling means the rock is moving. Sometimes that's gold. Sometimes that's your funeral.",
            "My pickaxe has been in my family for three generations.",
            "This pickaxe was my grandfather's, then my father's, now mine. It's outlasted both of them.",
            "Three generations of miners have swung this pickaxe. It knows the rock better than I do.",
            "Family heirloom, this. Not the prettiest tool, but it's never failed me. Steel like they don't make anymore.",
            "There's a seam of gold deep in tunnel 7, but it's dangerous.",
            "Tunnel 7 has a gold vein thick as your arm. But the air's bad down there and the ceiling groans.",
            "I've seen the gold in tunnel 7 with my own eyes. The problem is getting back out after you take it.",
            "Gold in tunnel 7 — enough to set you up for life. But three miners went in last year and only two came out.",
        ],
        "trades": [
            {"give": "stone", "give_qty": 10, "receive": "metal_scrap", "receive_qty": 2},
            {"give": "gems", "give_qty": 1, "receive": "torch", "receive_qty": 3},
        ],
        "quest": {"type": "mine", "item": "gems", "qty": 3, "reward": 500, "xp": 100, "desc": "Kate needs 3 rough gems for a special project"},
    },
    "chef_marie": {
        "name": "Chef Marie", "emoji": "👩‍🍳",
        "location": "market", "personality": "cheerful",
        "greeting": [
            "Bonjour! Hungry?",
            "Ah, bonjour! You arrive just as the soup is ready — perfect timing!",
            "Hello there! Your stomach is growling, I can hear it from here. Come in!",
            "Bonjour, mon ami! The kitchen is warm and the food is fresh. Sit!",
            "Ah, come in! I just made something special.",
            "Oh, perfect timing! I just pulled something from the oven. You'll love it.",
            "Come in, come in! Today's special is — well, it's a surprise. Trust me!",
            "You smell that? Fresh out of the pan. Come have a taste!",
            "You look like you need a good meal!",
            "Oh, you poor thing — when did you last eat? Sit down, I'll fix you something.",
            "You look half-starved! Don't worry, Chef Marie will take care of you.",
            "That look on your face says you haven't had a proper meal in days. Let me fix that.",
        ],
        "dialogue": [
            "Cooking is an art. You must feel the ingredients.",
            "You don't just follow recipes — you listen to the food. It tells you what it needs.",
            "Any fool can follow instructions. A real cook feels the dish in their bones.",
            "Cooking is painting you can eat. Every ingredient is a color, every spice is a brushstroke.",
            "Fresh herbs make all the difference, you know.",
            "Dried herbs are for emergencies. Fresh ones? That's where the magic lives.",
            "If you use dried basil, I can tell. Always fresh. Always. It changes everything.",
            "The herb garden is my treasure. Without fresh herbs, cooking is just... heating.",
            "I can teach you a recipe — if you bring me the right materials.",
            "Want to learn? Bring me herbs and I'll show you something your mother never taught you.",
            "I have a recipe that would make you weep with joy. But I need the right ingredients first.",
            "Cooking lessons? Of course! But you must bring me what I need. Quality in, quality out.",
            "The storm ruined my vegetable garden. Such is life!",
            "The storm flattened my garden — weeks of work, gone in one night. But we replant! We always replant.",
            "My tomatoes, my basil, my peppers — all underwater now. Ah well. The soil will dry and we start again.",
            "The garden is destroyed. But you know what they say — a chef is only as good as their next dish, not their last one.",
            "A good meal can change your whole day. Remember that.",
            "Never underestimate what a warm meal can do. It fixes the body and the soul at the same time.",
            "You come in sad, you leave happy. That's the power of food. Remember that.",
            "I've seen people walk in looking defeated and walk out smiling. All it took was the right dish.",
        ],
        "trades": [
            {"give": "herbs", "give_qty": 2, "receive": "herbal_meds", "receive_qty": 1},
            {"give": "fish", "give_qty": 2, "receive": "cooked_fish_item", "receive_qty": 2},
        ],
        "quest": {"type": "deliver", "item": "herbs", "qty": 8, "reward": 250, "xp": 60, "desc": "Marie needs 8 herbs for her signature dish"},
    },
    "mystic_elara": {
        "name": "Elara the Mystic", "emoji": "🔮",
        "location": "forest", "personality": "mysterious",
        "greeting": [
            "I sensed you coming...",
            "The crystals trembled before you arrived. I knew you would come.",
            "Your aura preceded you by several minutes. Interesting shade, that.",
            "I felt a disturbance in the veil moments ago. And here you are.",
            "The spirits whispered your name.",
            "The spirits have been restless all morning. Now I understand why — it's you.",
            "They speak of you in the other realm. Your name echoes in places you cannot see.",
            "The whispers said a traveler would arrive. They did not say what you carry with you.",
            "You seek knowledge, traveler?",
            "Your eyes ask questions your mouth hasn't spoken. Ask, and perhaps I will answer.",
            "Knowledge is a dangerous gift. Are you certain you want what you came for?",
            "You carry the weight of curiosity. That is both a blessing and a curse, traveler.",
        ],
        "dialogue": [
            "There are things in this world beyond your understanding.",
            "The veil between what you see and what is real is thinner than you think.",
            "Some truths would break your mind if you heard them. Be grateful for your ignorance.",
            "The world is far larger and far stranger than your eyes can show you.",
            "The weather is a reflection of the spiritual realm.",
            "When the storms rage, it is the spirits arguing. When the fog rolls in, they are hiding something.",
            "Every drop of rain is a tear from the other side. The weather tells their story.",
            "The sky mirrors what happens beyond the veil. Read the clouds and you read the spirit world.",
            "I see... a great fortune in your future. But also great danger.",
            "Your path forks ahead. One road leads to gold, the other to blood. You will walk both.",
            "The threads of your fate are tangled — great reward and great peril woven together. Tread carefully.",
            "I see wealth in your future, but it comes with a price. The universe always collects.",
            "Bring me gems, and I will read your fortune.",
            "Crystals focus the sight. Bring me gems and I will show you what tomorrow holds.",
            "The stones speak to me when I hold them. Bring gems, and I will translate.",
            "Gems are windows to the other side. Provide them, and I will open the curtain for you.",
            "The old ruins hold secrets. But not all secrets should be uncovered.",
            "The ruins remember things that were buried for a reason. Some doors are locked for your protection.",
            "There are chambers beneath the old stones that have not seen light in a thousand years. Perhaps that is for the best.",
            "The ruins whisper to those who listen. But some whispers drive the listener mad. Be careful what you ask of them.",
        ],
        "trades": [
            {"give": "gems", "give_qty": 2, "receive": "lucky_coin", "receive_qty": 1},
            {"give": "stone", "give_qty": 5, "receive": "torch", "receive_qty": 2},
        ],
        "quest": {"type": "explore", "item": "gems", "qty": 5, "reward": 600, "xp": 150, "desc": "Elara wants 5 gems from the ancient ruins for a ritual"},
    },
    "ranger_tom": {
        "name": "Ranger Tom", "emoji": "🧑‍🌾",
        "location": "forest", "personality": "friendly",
        "greeting": [
            "Nice day for a walk, isn't it?",
            "Beautiful day out here, isn't it? The forest is in a good mood.",
            "Can't beat a day like this on the trail. Perfect temperature, good breeze.",
            "What a gorgeous day! The kind that makes you glad to be outdoors.",
            "Mind the trails — some are overgrown.",
            "Watch your step on the north path — the brush has taken over since last spring.",
            "Some of the trails haven't been cleared in weeks. Watch for thorns and low branches.",
            "The east trail's getting overgrown again. I'll clear it when I can, but for now, step carefully.",
            "Always good to see a friendly face out here.",
            "Hey there! Always nice to run into someone who appreciates the outdoors.",
            "Well, hello! Good to see a familiar face on the trail. How've you been?",
            "Oh, it's you! Glad to see you out here. The forest is better with company.",
        ],
        "dialogue": [
            "I've seen bears in these woods. Keep your distance.",
            "Spotted a brown bear near the creek yesterday. Give them space and they'll leave you alone.",
            "There's a bear that roams these parts — big one. Don't run if you see it. Back away slowly.",
            "Bears in these woods, yes. They're not aggressive if you don't surprise them. Make noise as you walk.",
            "The foraging is excellent after rain. Try the meadow.",
            "Rain brings out the best in the forest. The meadow's full of mushrooms and berries right now.",
            "After a good rain, the foraging is unbeatable. Head to the meadow — bring a basket.",
            "Wet soil means rich pickings. The meadow's the place to go after a downpour.",
            "I maintain all the trails out here. It's a labor of love.",
            "Every trail you walk on, I've cleared at some point. It's hard work, but someone's got to do it.",
            "I built half these paths myself. Keeps me busy, keeps me connected to the land.",
            "Trail maintenance is my calling. It's not glamorous, but when I see someone enjoying the path, it's worth it.",
            "If you're exploring, bring a compass. People get lost.",
            "The forest looks the same in every direction once you're deep in. Bring a compass — seriously.",
            "I've rescued three people this month who wandered off without a compass. Don't be the fourth.",
            "Take a compass. The trees don't have signs, and the sun isn't always visible through the canopy.",
            "Saw some strange tracks near the canyon yesterday. Big ones.",
            "Found tracks near the canyon — not bear, not deer. Something else. Big. Three toes.",
            "There were tracks by the canyon rim yesterday. Deep ones. Whatever made them was heavy.",
            "I don't know what left those tracks near the canyon. I'm not sure I want to know.",
        ],
        "trades": [
            {"give": "wood", "give_qty": 5, "receive": "rope", "receive_qty": 1},
            {"give": "herbs", "give_qty": 3, "receive": "bandage", "receive_qty": 1},
        ],
        "quest": {"type": "explore", "item": "wood", "qty": 15, "reward": 350, "xp": 90, "desc": "Tom needs 15 wood to repair the trail bridges"},
    },
    "blacksmith_gus": {
        "name": "Gus the Blacksmith", "emoji": "🧑‍🏭",
        "location": "market", "personality": "gruff",
        "greeting": [
            "What do you need?",
            "Spit it out. I've got iron to fold.",
            "State your business. The forge doesn't wait.",
            "Well? I'm listening. Make it worth stopping for.",
            "Make it quick, I'm busy.",
            "I've got three orders backed up. Talk fast.",
            "No time for small talk. What do you need forged?",
            "The metal won't shape itself. What do you want?",
            "Don't touch the forge.",
            "Hands off the forge. That's not a request.",
            "Touch the forge and you'll pull back a stump. Fair warning.",
            "The forge is hot enough to melt bone. Keep your hands where I can see them.",
        ],
        "dialogue": [
            "Good metal is hard to find these days.",
            "Quality ore? Scarce. Everyone's digging for gems, nobody's mining iron anymore.",
            "Finding decent metal these days is like finding water in a desert. Everyone wants it, nobody's got it.",
            "The metal coming through here lately is scrap. Barely worth the heat to melt it.",
            "I can sharpen your tools — for a price.",
            "Dull blade? I can fix that. Won't be free, but it'll be fair.",
            "Tool sharpening is five coins per edge. No discounts, no exceptions.",
            "You bring it, I'll sharpen it. Payment up front. I've been stiffed before.",
            "The storm damaged my anvil. Cost me a week's work.",
            "Storm cracked my anvil clean down the middle. Took a week to fix. Lost every order I had.",
            "Lightning hit the workshop. Anvil's warped now. I can still work, but it's never been the same.",
            "The storm ruined my main anvil. I'm using the backup, but it's like writing with your wrong hand.",
            "You bring me metal scrap, I'll make it worth your while.",
            "Metal scrap — I'll take all you've got. Good price too. I'm always short on raw material.",
            "Scrap metal is worth more than you think. Bring me a pile and we'll do business.",
            "I need metal scrap. You need coin. Let's help each other out.",
            "A legendary pickaxe? Maybe. If you bring me the right materials.",
            "You want a legendary tool? Bring me rare ore — the kind you only find in dangerous places. Then we'll talk.",
            "I've heard of legendary pickaxes. Could I forge one? Possibly. But not with common iron. Bring me something special.",
            "A mythic-grade tool requires mythic-grade materials. You bring the ore, I'll bring the skill.",
        ],
        "trades": [
            {"give": "metal_scrap", "give_qty": 5, "receive": "stone", "receive_qty": 10},
            {"give": "metal_scrap", "give_qty": 10, "receive": "rope", "receive_qty": 2},
        ],
        "quest": {"type": "deliver", "item": "metal_scrap", "qty": 20, "reward": 400, "xp": 100, "desc": "Gus needs 20 metal scrap to forge a special tool"},
    },
    "drifter_vex": {
        "name": "Vex the Drifter", "emoji": "🧥",
        "location": "alley", "personality": "suspicious",
        "greeting": [
            "...You shouldn't be here.",
            "This isn't a place for the curious. Turn back if you know what's good for you.",
            "Wrong alley, friend. Unless you're here on purpose. In which case... proceed.",
            "You're a long way from the market. People who end up here usually aren't looking for vegetables.",
            "Keep your voice down.",
            "Lower your voice. Sound carries in these alleys.",
            "Shh. Not so loud. The walls have listeners.",
            "Quiet. The less noise we make, the less attention we draw. Understand?",
            "What do you want?",
            "State your business quickly. I don't like lingerers.",
            "You came looking for me, so you know what I am. What do you need?",
            "Talk fast. I don't do pleasantries and I don't do repeat customers who overstay.",
        ],
        "dialogue": [
            "There are easier ways to make money. Dangerous ones.",
            "You want coin without the grind? There are ways. Not legal ones. But ways.",
            "Some people earn. Some people take. I'm not judging either way. Just saying.",
            "Easy money exists. It's just... complicated. And it comes with risks you can't undo.",
            "The fog is perfect for... certain activities.",
            "Foggy nights? Best time to move unseen. If you catch my meaning.",
            "When the fog rolls in, even the streetlights can't help you see. Useful, that.",
            "Thick fog means no witnesses. No witnesses means no problems. Make of that what you will.",
            "I know people. I know things. That's all you need to know.",
            "Information is my trade. I know who's buying, who's selling, and who's looking for both.",
            "I have contacts in places you've never heard of. Don't ask names. Don't ask how.",
            "Knowing things is what keeps me alive. Knowing the right things, at the right time. That's power.",
            "Stormy nights are the best nights. Nobody's watching.",
            "When the thunder rolls, the guards stay indoors. Convenient, isn't it?",
            "Storm means empty streets. Empty streets mean opportunity. If you're bold enough.",
            "The worse the weather, the fewer the eyes. Something to keep in mind.",
            "You didn't see me. I wasn't here. Understand?",
            "Forget this conversation happened. Forget you walked down this alley. Forget my face.",
            "If anyone asks, we've never met. You were never here. I was never here. Clear?",
            "This meeting never occurred. We are strangers. That's how it works in my world.",
        ],
        "trades": [
            {"give": "cloth", "give_qty": 3, "receive": "lockpick", "receive_qty": 1},
            {"give": "metal_scrap", "give_qty": 3, "receive": "torch", "receive_qty": 1},
        ],
        "quest": {"type": "crime", "item": "any", "qty": 5, "reward": 500, "xp": 120, "desc": "Vex wants you to commit 5 crimes to prove you're useful"},
    },
}
