QUEST_TEMPLATES = [
    {"desc": "Work {n} times",           "type": "work",       "target": lambda n: n,  "range": (1, 3),   "reward": (50, 150)},
    {"desc": "Gamble {n} times",         "type": "gamble",     "target": lambda n: n,  "range": (1, 5),   "reward": (25, 100)},
    {"desc": "Buy {n} items from store", "type": "buy",        "target": lambda n: n,  "range": (1, 3),   "reward": (40, 125)},
    {"desc": "Earn {n} coins",           "type": "earn",       "target": lambda n: n,  "range": (200, 1000), "reward": (25, 100)},
    {"desc": "Commit {n} crimes",        "type": "crime",      "target": lambda n: n,  "range": (1, 3),   "reward": (50, 175)},
    {"desc": "Use {n} items",            "type": "use_item",   "target": lambda n: n,  "range": (1, 5),   "reward": (25, 75)},
    {"desc": "Fish {n} times",           "type": "fish",       "target": lambda n: n,  "range": (1, 5),   "reward": (40, 150)},
    {"desc": "Mine {n} times",           "type": "mine",       "target": lambda n: n,  "range": (1, 3),   "reward": (50, 175)},
    {"desc": "Explore {n} times",        "type": "explore",    "target": lambda n: n,  "range": (1, 3),   "reward": (75, 200)},
    {"desc": "Craft {n} items",          "type": "craft",      "target": lambda n: n,  "range": (1, 3),   "reward": (50, 150)},
    {"desc": "Complete {n} co-op shifts", "type": "coop",      "target": lambda n: n,  "range": (1, 2),   "reward": (100, 300)},
]

QUESTS = {
    "work_3":      {"name": "Hard Worker",       "description": "Work 3 times",            "target": 3,   "reward": 100,  "xp": 25,  "type": "work"},
    "work_5":      {"name": "Dedicated Employee","description": "Work 5 times",            "target": 5,   "reward": 200,  "xp": 50,  "type": "work"},
    "gamble_3":    {"name": "Risk Taker",        "description": "Gamble 3 times",          "target": 3,   "reward": 75,   "xp": 25,  "type": "gamble"},
    "gamble_5":    {"name": "Lucky Streak",      "description": "Gamble 5 times",          "target": 5,   "reward": 150,  "xp": 40,  "type": "gamble"},
    "buy_2":       {"name": "Shopping Spree",    "description": "Buy 2 items from store",  "target": 2,   "reward": 75,   "xp": 25,  "type": "buy"},
    "buy_5":       {"name": "Shopaholic",        "description": "Buy 5 items from store",  "target": 5,   "reward": 175,  "xp": 40,  "type": "buy"},
    "earn_500":    {"name": "Money Maker",       "description": "Earn 500 coins",          "target": 500, "reward": 100,  "xp": 30,  "type": "earn"},
    "earn_1000":   {"name": "Big Earner",        "description": "Earn 1,000 coins",        "target": 1000,"reward": 200,  "xp": 50,  "type": "earn"},
    "crime_2":     {"name": "Petty Criminal",    "description": "Commit 2 crimes",         "target": 2,   "reward": 125,  "xp": 30,  "type": "crime"},
    "crime_5":     {"name": "Crime Spree",       "description": "Commit 5 crimes",         "target": 5,   "reward": 250,  "xp": 60,  "type": "crime"},
    "use_3":       {"name": "Item User",         "description": "Use 3 items",             "target": 3,   "reward": 50,   "xp": 20,  "type": "use_item"},
    "use_5":       {"name": "Consumer",           "description": "Use 5 items",             "target": 5,   "reward": 100,  "xp": 30,  "type": "use_item"},
    "earn_2500":   {"name": "Big Spender Quest",  "description": "Earn 2,500 coins",        "target": 2500,"reward": 400,  "xp": 80,  "type": "earn"},
    "work_10":     {"name": "Workaholic",        "description": "Work 10 times",           "target": 10,  "reward": 350,  "xp": 75,  "type": "work"},
    "gamble_10":   {"name": "High Roller Quest",  "description": "Gamble 10 times",         "target": 10,  "reward": 250,  "xp": 60,  "type": "gamble"},
    "buy_10":      {"name": "Bulk Buyer",        "description": "Buy 10 items from store", "target": 10,  "reward": 300,  "xp": 60,  "type": "buy"},
    "crime_10":    {"name": "Crime Lord Quest",   "description": "Commit 10 crimes",        "target": 10,  "reward": 400,  "xp": 80,  "type": "crime"},
    "use_10":      {"name": "Power User",        "description": "Use 10 items",            "target": 10,  "reward": 175,  "xp": 40,  "type": "use_item"},
}
