"""RPG Stats System — 8 core stats, training, qualifications, booster items."""

STATS = {
    "strength":     {"name": "💪 Strength",     "short": "STR", "emoji": "💪", "description": "Physical power. Heavy labor, construction, trades."},
    "intelligence": {"name": "🧠 Intelligence", "short": "INT", "emoji": "🧠", "description": "Mental capacity. Tech, medical, science, business."},
    "dexterity":    {"name": "🫰 Dexterity",    "short": "DEX", "emoji": "🫰", "description": "Hand-eye coordination. Creative, service, precision jobs."},
    "perception":   {"name": "👁️ Perception",   "short": "PER", "emoji": "👁️", "description": "Awareness, observation. Medical diagnosis, driving, security."},
    "endurance":    {"name": "🏃 Endurance",    "short": "END", "emoji": "🏃", "description": "Stamina, physical resilience. Long shifts, physical jobs."},
    "charisma":     {"name": "🗣️ Charisma",     "short": "CHA", "emoji": "🗣️", "description": "Social skills. Service, business, negotiation, sales."},
    "luck":         {"name": "🍀 Luck",         "short": "LCK", "emoji": "🍀", "description": "Random events, rare finds, gambling, tips."},
    "focus":        {"name": "🎯 Focus",        "short": "FOC", "emoji": "🎯", "description": "Concentration, minigame performance, accuracy."},
}

STAT_KEYS = list(STATS.keys())
BASE_STAT_VALUE = 10
MAX_STAT_VALUE = 100

TRAINING_CONFIG = {
    "cost_formula": "100 * (stat_level / 10)",
    "energy_cost": 25,
    "cooldown_seconds": 3600,
    "min_gain": 1,
    "max_gain": 3,
    "cost_cap": 2000,
}

QUALIFICATIONS = {
    "drivers_license": {
        "name": "🚗 Driver's License",
        "description": "Required for driving and transport jobs.",
        "cost": 500,
        "sessions": 3,
        "cooldown_seconds": 7200,
        "stat_reqs": {"perception": 15},
        "qual_reqs": [],
        "stat_rewards": {"perception": 3},
    },
    "commercial_license": {
        "name": "🚛 Commercial License",
        "description": "Required for heavy transport and logistics jobs.",
        "cost": 2000,
        "sessions": 5,
        "cooldown_seconds": 7200,
        "stat_reqs": {"perception": 25, "endurance": 20},
        "qual_reqs": ["drivers_license"],
        "stat_rewards": {"perception": 3, "endurance": 2},
    },
    "pilot_license": {
        "name": "✈️ Pilot License",
        "description": "Required for aviation jobs.",
        "cost": 8000,
        "sessions": 8,
        "cooldown_seconds": 14400,
        "stat_reqs": {"perception": 40, "focus": 35, "intelligence": 30},
        "qual_reqs": ["drivers_license"],
        "stat_rewards": {"perception": 5, "focus": 3, "intelligence": 2},
    },
    "food_safety_cert": {
        "name": "🍽️ Food Safety Certificate",
        "description": "Required for food service and kitchen jobs.",
        "cost": 800,
        "sessions": 3,
        "cooldown_seconds": 7200,
        "stat_reqs": {"dexterity": 15, "perception": 10},
        "qual_reqs": [],
        "stat_rewards": {"dexterity": 3, "perception": 2},
    },
    "welding_cert": {
        "name": "🔧 Welding Certification",
        "description": "Required for advanced trades and metalwork.",
        "cost": 1500,
        "sessions": 4,
        "cooldown_seconds": 7200,
        "stat_reqs": {"strength": 25, "dexterity": 20, "focus": 15},
        "qual_reqs": [],
        "stat_rewards": {"strength": 3, "dexterity": 2, "focus": 2},
    },
    "hvac_cert": {
        "name": "❄️ HVAC Certification",
        "description": "Required for HVAC and climate system jobs.",
        "cost": 1800,
        "sessions": 4,
        "cooldown_seconds": 7200,
        "stat_reqs": {"strength": 20, "intelligence": 20, "dexterity": 15},
        "qual_reqs": [],
        "stat_rewards": {"strength": 2, "intelligence": 3, "dexterity": 2},
    },
    "electrical_cert": {
        "name": "⚡ Electrical Certification",
        "description": "Required for electrician and electrical engineering jobs.",
        "cost": 2500,
        "sessions": 5,
        "cooldown_seconds": 10800,
        "stat_reqs": {"intelligence": 30, "dexterity": 25, "focus": 20},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 4, "dexterity": 2, "focus": 2},
    },
    "medical_degree": {
        "name": "⚕️ Medical Degree",
        "description": "Required for doctor and surgeon jobs.",
        "cost": 15000,
        "sessions": 10,
        "cooldown_seconds": 21600,
        "stat_reqs": {"intelligence": 45, "perception": 40, "focus": 35},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 5, "perception": 4, "focus": 3},
    },
    "nursing_degree": {
        "name": "💉 Nursing Degree",
        "description": "Required for nursing and medical support jobs.",
        "cost": 6000,
        "sessions": 7,
        "cooldown_seconds": 14400,
        "stat_reqs": {"intelligence": 30, "perception": 25, "endurance": 25},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 4, "perception": 3, "endurance": 2},
    },
    "pharmacy_cert": {
        "name": "💊 Pharmacy Certification",
        "description": "Required for pharmacist and pharmacy tech jobs.",
        "cost": 4000,
        "sessions": 6,
        "cooldown_seconds": 10800,
        "stat_reqs": {"intelligence": 35, "focus": 30, "perception": 25},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 4, "focus": 3, "perception": 2},
    },
    "cs_degree": {
        "name": "💻 Computer Science Degree",
        "description": "Required for programmer and software engineering jobs.",
        "cost": 10000,
        "sessions": 9,
        "cooldown_seconds": 21600,
        "stat_reqs": {"intelligence": 40, "focus": 35, "dexterity": 20},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 5, "focus": 3, "dexterity": 2},
    },
    "engineering_degree": {
        "name": "⚙️ Engineering Degree",
        "description": "Required for engineering and advanced tech jobs.",
        "cost": 12000,
        "sessions": 10,
        "cooldown_seconds": 21600,
        "stat_reqs": {"intelligence": 40, "dexterity": 30, "focus": 30, "strength": 20},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 4, "dexterity": 3, "focus": 2, "strength": 2},
    },
    "business_degree": {
        "name": "📊 Business Degree",
        "description": "Required for management and finance jobs.",
        "cost": 8000,
        "sessions": 8,
        "cooldown_seconds": 14400,
        "stat_reqs": {"intelligence": 35, "charisma": 35, "focus": 25},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 3, "charisma": 4, "focus": 2},
    },
    "mba": {
        "name": "🎓 MBA (Master of Business)",
        "description": "Required for CEO and executive jobs.",
        "cost": 30000,
        "sessions": 12,
        "cooldown_seconds": 21600,
        "stat_reqs": {"intelligence": 50, "charisma": 50, "focus": 40},
        "qual_reqs": ["business_degree"],
        "stat_rewards": {"intelligence": 4, "charisma": 5, "focus": 3},
    },
    "art_degree": {
        "name": "🎨 Fine Arts Degree",
        "description": "Required for professional creative and design jobs.",
        "cost": 6000,
        "sessions": 7,
        "cooldown_seconds": 14400,
        "stat_reqs": {"dexterity": 35, "perception": 30, "charisma": 20},
        "qual_reqs": [],
        "stat_rewards": {"dexterity": 4, "perception": 3, "charisma": 2},
    },
    "security_cert": {
        "name": "🛡️ Security Certification",
        "description": "Required for security and law enforcement jobs.",
        "cost": 2000,
        "sessions": 5,
        "cooldown_seconds": 10800,
        "stat_reqs": {"strength": 25, "perception": 25, "endurance": 20},
        "qual_reqs": [],
        "stat_rewards": {"strength": 3, "perception": 3, "endurance": 2},
    },
    "military_training": {
        "name": "🎖️ Military Training",
        "description": "Required for military and defense jobs.",
        "cost": 5000,
        "sessions": 8,
        "cooldown_seconds": 14400,
        "stat_reqs": {"strength": 35, "endurance": 35, "focus": 25, "perception": 25},
        "qual_reqs": [],
        "stat_rewards": {"strength": 4, "endurance": 4, "focus": 2, "perception": 2},
    },
    "apprenticeship": {
        "name": "🔨 Trade Apprenticeship",
        "description": "Required for journeyman and master trades jobs.",
        "cost": 3000,
        "sessions": 6,
        "cooldown_seconds": 10800,
        "stat_reqs": {"strength": 25, "dexterity": 25, "focus": 20},
        "qual_reqs": [],
        "stat_rewards": {"strength": 3, "dexterity": 3, "focus": 2},
    },
    "teaching_cert": {
        "name": "📚 Teaching Certificate",
        "description": "Required for education and tutoring jobs.",
        "cost": 4000,
        "sessions": 6,
        "cooldown_seconds": 10800,
        "stat_reqs": {"intelligence": 30, "charisma": 30, "focus": 25},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 3, "charisma": 3, "focus": 2},
    },
    "law_degree": {
        "name": "⚖️ Law Degree",
        "description": "Required for lawyer and legal jobs.",
        "cost": 18000,
        "sessions": 11,
        "cooldown_seconds": 21600,
        "stat_reqs": {"intelligence": 45, "charisma": 40, "focus": 35},
        "qual_reqs": [],
        "stat_rewards": {"intelligence": 5, "charisma": 3, "focus": 3},
    },
}

STAT_BOOSTER_ITEMS = {
    "protein_shake": {
        "name": "🥤 Protein Shake", "price": 150, "type": "stat_booster",
        "stat": "strength", "boost": 10, "duration_minutes": 30,
    },
    "nootropic": {
        "name": "🧠 Nootropic Supplement", "price": 300, "type": "stat_booster",
        "stat": "intelligence", "boost": 15, "duration_minutes": 60,
    },
    "caffeine_pill": {
        "name": "💊 Caffeine Pill", "price": 120, "type": "stat_booster",
        "stat": "focus", "boost": 10, "duration_minutes": 45,
    },
    "lucky_rabbit_foot": {
        "name": "🐇 Lucky Rabbit Foot", "price": 500, "type": "stat_booster",
        "stat": "luck", "boost": 15, "duration_minutes": 60,
    },
    "confidence_potion": {
        "name": "🍸 Confidence Potion", "price": 250, "type": "stat_booster",
        "stat": "charisma", "boost": 12, "duration_minutes": 30,
    },
    "eye_drops": {
        "name": "👁️ Eye Drops", "price": 80, "type": "stat_booster",
        "stat": "perception", "boost": 10, "duration_minutes": 30,
    },
    "hand_warmup_cream": {
        "name": "🧴 Hand Warm-up Cream", "price": 60, "type": "stat_booster",
        "stat": "dexterity", "boost": 10, "duration_minutes": 20,
    },
    "endurance_shot": {
        "name": "💉 Endurance Shot", "price": 180, "type": "stat_booster",
        "stat": "endurance", "boost": 12, "duration_minutes": 30,
    },
}
